spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${QELLO_DB_HOST:localhost}:${QELLO_DB_PORT:5432}/${QELLO_DB_NAME:qello}
spring.datasource.username=${QELLO_DB_USERNAME:qello}
spring.datasource.password=${QELLO_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=5000
