package com.dnd.qello.notification.domain;

public enum NotificationType {
	ANSWER_RECEIVED,
	ANSWER_REACTED,
	DIRECTION_POST_RECEIVED,
	REPORT_RESOLVED,
	QUESTION_PROPOSAL_REVIEWED,
	QUESTION_RECOMMENDED
}
