package com.dnd.qello.notification.domain;

public enum OutboxEventType {
	RECIPIENT_MATCH_REQUESTED,
	RECIPIENTS_CONFIRMED,
	DIRECTION_POST_EXPIRED,
	ANSWER_PUBLISHED,
	DAILY_QUESTION_ASSIGNED,
	QUESTION_PROPOSAL_REVIEWED,
	REPORT_RESOLVED
}
