package com.dnd.qello.notification.domain;

public enum OutboxEventType {
	RECIPIENT_MATCH_REQUESTED,
	RECIPIENTS_CONFIRMED,
	DIRECTION_POST_EXPIRED,
	ANSWER_PUBLISHED,
	ANSWER_REACTED,
	SKIP_CONFIRMATION_DUE,
	QUESTION_RECOMMENDED,
	QUESTION_PROPOSAL_REVIEWED,
	REPORT_RESOLVED,
	MODERATION_EXECUTION_REQUESTED,
	MODERATION_VERDICT_READY,
	MODERATION_DEADLINE_ELAPSED
}
