-- 필터링 시스템(자동 콘텐츠 모더레이션)의 도메인 기반 스키마. GitHub #103(F00).
--
-- 이 시스템은 answer/user_account 테이블을 소유하지 않는다. target_type과 target_id로
-- 호출자 도메인의 대상을 가리킬 뿐, 그 값을 해석하거나 FK로 참조하지 않는다.
-- target_version은 콘텐츠 revision을 표현하기 위해 남겨둔 자리이며, 현재는 편집
-- 기능이 없어 항상 0을 쓴다. 편집 기능이 결정되면 그때 의미를 채운다.
--
-- filter_release는 이 마이그레이션에서 식별자만 만든다. 정규화 규칙, 로컬 사전,
-- category mapping·threshold, model snapshot을 묶는 실제 registry 컬럼은 #104(F01)가
-- ALTER TABLE로 추가한다. manual_review_case와 appeal_case도 마찬가지로 우선순위·
-- reviewer 배정 같은 워크플로 컬럼은 각각 #110(F07), #112(F10)가 추가한다.
CREATE TABLE filter_release (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

COMMENT ON TABLE filter_release IS
    '모더레이션 정책 구성요소(정규화 규칙·로컬 사전·threshold·model snapshot)를 묶는 식별자. #104가 registry 컬럼을 추가한다.';

-- moderation job. INV-GEN-001~005의 authority 검증 대상.
--
-- attempt_generation은 emergency migration(#109) 이후에만 증가한다. 그 미만
-- generation으로 도착한 결과는 요청 접수 자체에서 거절한다(도메인 계층에서
-- ApplicationException 발생, 이 테이블에는 애초에 반영되지 않는다).
CREATE TABLE filter_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type         VARCHAR(20) NOT NULL,
    target_id           BIGINT NOT NULL,
    target_version      BIGINT NOT NULL DEFAULT 0,
    filter_release_id   BIGINT NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'AUTOMATED',
    attempt_generation  INT NOT NULL DEFAULT 1,
    manually_resolved   BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_verdict    VARCHAR(10),
    idempotency_key     VARCHAR(200) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_filter_job_release
        FOREIGN KEY (filter_release_id) REFERENCES filter_release (id),
    CONSTRAINT ck_filter_job_target_type
        CHECK (target_type IN ('ANSWER', 'NICKNAME')),
    CONSTRAINT ck_filter_job_status
        CHECK (status IN ('AUTOMATED', 'RETRY_EXHAUSTED', 'MANUAL_REVIEW_REQUIRED', 'RESOLVED')),
    CONSTRAINT ck_filter_job_attempt_generation
        CHECK (attempt_generation > 0),
    CONSTRAINT ck_filter_job_resolved_verdict
        CHECK (resolved_verdict IN ('ALLOW', 'BLOCK')),
    CONSTRAINT ck_filter_job_resolved_has_verdict
        CHECK ((status = 'RESOLVED') = (resolved_verdict IS NOT NULL)),
    CONSTRAINT ck_filter_job_manual_implies_resolved
        CHECK (NOT manually_resolved OR status = 'RESOLVED')
);

-- 같은 트리거(예: 같은 답변 제출, 같은 deadline scheduler tick)가 중복 호출돼도
-- job이 하나만 생기게 하는 멱등키. 호출자가 target·release·트리거 성격을 조합해 만든다.
CREATE UNIQUE INDEX uq_filter_job_idempotency_key
    ON filter_job (idempotency_key);

CREATE INDEX filter_job_target_idx
    ON filter_job (target_type, target_id, target_version);

COMMENT ON TABLE filter_job IS
    'moderation job의 authority 상태(currentAttemptGeneration, manuallyResolved)를 소유한다. 공개 여부는 이 테이블에 없다 — 호출자 도메인에 콜백으로만 전달한다.';
COMMENT ON COLUMN filter_job.target_version IS
    '현재 항상 0. 편집·revision 기능이 결정되면 그때부터 의미를 갖는다.';

-- job 상태 변경 이력. INV-GEN의 "상태 변경 이력과 감사 이벤트" 요구를 충족하는
-- append-only 로그. 도메인 계층은 이 테이블에 쓰지 않고, 호출 서비스가 상태 전이
-- 직후 같은 트랜잭션에서 기록한다.
CREATE TABLE filter_job_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_job_id   BIGINT NOT NULL,
    from_status     VARCHAR(30),
    to_status       VARCHAR(30) NOT NULL,
    reason          VARCHAR(200),
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_filter_job_status_history_job
        FOREIGN KEY (filter_job_id) REFERENCES filter_job (id)
);

CREATE INDEX filter_job_status_history_job_idx
    ON filter_job_status_history (filter_job_id);

-- pipeline attempt 하나의 원시 결과. filter_job.resolved_verdict가 "현재 권위 있는
-- 요약"이라면, 이 테이블은 "실제로 무슨 일이 있었는지"의 append-only 원장이다.
-- (filter_job_id, attempt_generation) 유일성이 같은 attempt의 중복 기록을 막는다.
CREATE TABLE filter_decision (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_job_id           BIGINT NOT NULL,
    attempt_generation      INT NOT NULL,
    verdict                 VARCHAR(10) NOT NULL,
    requested_release_id    BIGINT NOT NULL,
    actual_model            VARCHAR(100),
    decided_at              TIMESTAMPTZ NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_filter_decision_job
        FOREIGN KEY (filter_job_id) REFERENCES filter_job (id),
    CONSTRAINT fk_filter_decision_requested_release
        FOREIGN KEY (requested_release_id) REFERENCES filter_release (id),
    CONSTRAINT ck_filter_decision_verdict
        CHECK (verdict IN ('ALLOW', 'BLOCK'))
);

CREATE UNIQUE INDEX uq_filter_decision_job_attempt
    ON filter_decision (filter_job_id, attempt_generation);

COMMENT ON COLUMN filter_decision.actual_model IS
    '요청한 release가 아니라 공급자 응답이 실제로 보고한 model. release와 다를 수 있어 함께 기록한다(INV-REL-005).';

-- 수동 검토 case의 정체성과 유일성만 소유한다. 우선순위 계산, band, reviewer 배정,
-- FIFO/aging은 #110(F07)이 컬럼을 추가해 구현한다.
CREATE TABLE manual_review_case (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type         VARCHAR(20) NOT NULL,
    target_id           BIGINT NOT NULL,
    target_version      BIGINT NOT NULL DEFAULT 0,
    filter_release_id   BIGINT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_manual_review_case_release
        FOREIGN KEY (filter_release_id) REFERENCES filter_release (id),
    CONSTRAINT ck_manual_review_case_target_type
        CHECK (target_type IN ('ANSWER', 'NICKNAME'))
);

-- 동일 대상·release에 case를 하나만 만든다(INV-MAN-001). 이 unique index 자체가
-- "멱등 생성"의 구현이다 — 애플리케이션은 유일성 위반을 잡아 기존 case를 반환한다.
CREATE UNIQUE INDEX uq_manual_review_case_target
    ON manual_review_case (target_type, target_id, target_version, filter_release_id);

-- 작성자 이의제기의 정체성과 유일성만 소유한다. 6개월 만료, UPHOLD/OVERTURN 결과,
-- 통지 시각은 #112(F10)가 컬럼을 추가해 구현한다.
CREATE TABLE appeal_case (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type         VARCHAR(20) NOT NULL,
    target_id           BIGINT NOT NULL,
    filter_decision_id  BIGINT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_appeal_case_decision
        FOREIGN KEY (filter_decision_id) REFERENCES filter_decision (id),
    CONSTRAINT ck_appeal_case_target_type
        CHECK (target_type IN ('ANSWER', 'NICKNAME'))
);

-- 동일 대상·HIDDEN decision에 활성 appeal을 하나만 둔다(INV-APL-002).
CREATE UNIQUE INDEX uq_appeal_case_target_decision
    ON appeal_case (target_type, target_id, filter_decision_id);
