-- moderation release registry. GitHub #104(F01).
--
-- V10(#103)이 filter_release를 식별자만 있는 최소 테이블로 만들었다. 이 마이그레이션이
-- 그 위에 실제 registry 컬럼(정규화 규칙·로컬 사전·threshold·model snapshot 참조와
-- 승격 상태)을 추가한다. 각 참조 컬럼은 실제 규칙·사전·threshold 값을 담지 않고
-- 그 값이 어디에 있는지 가리키는 opaque 문자열이다 — 실제 정규화 규칙과 threshold
-- 확정은 별도 설계 게이트를 거친다.
ALTER TABLE filter_release
    ADD COLUMN normalization_ref     VARCHAR(200),
    ADD COLUMN local_ruleset_ref     VARCHAR(200),
    ADD COLUMN category_mapping_ref  VARCHAR(200),
    ADD COLUMN model_snapshot        VARCHAR(200),
    ADD COLUMN status                VARCHAR(20) NOT NULL DEFAULT 'CANDIDATE',
    ADD COLUMN promoted_at           TIMESTAMPTZ;

-- V10 시점에 만들어진 행은 없다(#103은 스키마만 만들고 데이터를 넣지 않았다)는 전제로
-- NOT NULL을 바로 건다. 있었다면 이 ALTER가 실패해 조용히 넘어가지 않는다.
ALTER TABLE filter_release
    ALTER COLUMN normalization_ref SET NOT NULL,
    ALTER COLUMN local_ruleset_ref SET NOT NULL,
    ALTER COLUMN category_mapping_ref SET NOT NULL,
    ALTER COLUMN model_snapshot SET NOT NULL;

ALTER TABLE filter_release
    ADD CONSTRAINT ck_filter_release_status
        CHECK (status IN ('CANDIDATE', 'OFFLINE_EVALUATED', 'SHADOW', 'CANARY', 'PROMOTED', 'ROLLED_BACK')),
    ADD CONSTRAINT ck_filter_release_promoted_at
        CHECK ((status = 'PROMOTED') = (promoted_at IS NOT NULL));

-- INV-REL-001·INV-REL-008의 DB측 강제: 동시에 PROMOTED인 release는 하나뿐이다.
-- `latest` alias나 자동 교체 경로가 없다는 것을 이 unique index 자체가 보장한다 —
-- 두 번째 PROMOTED 시도는 여기서 거절되고, registry 서비스는 먼저 기존 PROMOTED
-- release를 ROLLED_BACK으로 내린 뒤에만 새 release를 PROMOTED로 올릴 수 있다.
CREATE UNIQUE INDEX uq_filter_release_single_promoted
    ON filter_release ((true))
    WHERE status = 'PROMOTED';

CREATE INDEX filter_release_status_idx
    ON filter_release (status);

COMMENT ON COLUMN filter_release.normalization_ref IS
    '정규화 규칙 정의를 가리키는 opaque 참조. 이 시스템은 값을 해석하지 않는다.';
COMMENT ON COLUMN filter_release.local_ruleset_ref IS
    '고신뢰 로컬 규칙·사전 정의를 가리키는 opaque 참조.';
COMMENT ON COLUMN filter_release.category_mapping_ref IS
    'category mapping·threshold 정의를 가리키는 opaque 참조.';
COMMENT ON COLUMN filter_release.model_snapshot IS
    '요청 시 사용할 고정 OpenAI Moderation API snapshot 식별자. latest 같은 alias는
    애플리케이션이 값 검증에서 거절한다.';

-- release 승격·rollback 이력. 승인 없는 교체가 없었음을 감사할 수 있게 append-only로
-- 남긴다. release_id 삭제는 없으므로 FK에 ON DELETE 절을 두지 않는다.
CREATE TABLE release_promotion_history (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id                  BIGINT NOT NULL,
    action                      VARCHAR(20) NOT NULL,
    previous_active_release_id BIGINT,
    operator_user_id            BIGINT NOT NULL,
    occurred_at                 TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_release_promotion_history_release
        FOREIGN KEY (release_id) REFERENCES filter_release (id),
    CONSTRAINT fk_release_promotion_history_previous_release
        FOREIGN KEY (previous_active_release_id) REFERENCES filter_release (id),
    CONSTRAINT ck_release_promotion_history_action
        CHECK (action IN ('PROMOTE', 'ROLLBACK'))
);

CREATE INDEX release_promotion_history_release_idx
    ON release_promotion_history (release_id);

COMMENT ON TABLE release_promotion_history IS
    'release 승격·rollback 감사 이력. 운영자가 명시적으로 호출한 승격·rollback만 기록한다.';
COMMENT ON COLUMN release_promotion_history.operator_user_id IS
    '승격·rollback을 실행한 운영자의 user_account.id. 이 테이블은 user_account를
    FK로 참조하지 않는다 — filtering 시스템은 다른 도메인 테이블을 참조하지 않는다는
    #103의 경계를 여기서도 지킨다.';
