-- #109: OpenAI moderation snapshot 단위 health와 emergency migration.
--
-- snapshot_health는 model_snapshot 문자열(filter_release.model_snapshot과 같은 값
-- 도메인) 단위로 건강 상태를 추적한다. 개별 filter_job 실패가 아니라 synthetic
-- probe 결과로만 전이한다(INV-HLT-001). PERMANENT_CONFIRMED는 운영자의 명시적
-- 승인으로만 도달할 수 있다(INV-HLT-005) — 이 CHECK 제약은 그 상태와 승인 컬럼이
-- 함께 있어야 함만 강제하고, 실제 전이 경로 제한은 애플리케이션 계층이 강제한다.
CREATE TABLE snapshot_health (
    model_snapshot                  VARCHAR(200) PRIMARY KEY,
    status                          VARCHAR(20) NOT NULL DEFAULT 'HEALTHY',
    target_only_failure_count       INT NOT NULL DEFAULT 0,
    first_target_only_failure_at    TIMESTAMPTZ,
    last_target_only_failure_at     TIMESTAMPTZ,
    official_announcement           BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_at                    TIMESTAMPTZ,
    confirmed_by_operator_user_id   BIGINT,
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT ck_snapshot_health_status
        CHECK (status IN ('HEALTHY', 'PERMANENT_SUSPECTED', 'PERMANENT_CONFIRMED')),
    CONSTRAINT ck_snapshot_health_target_only_failure_count
        CHECK (target_only_failure_count >= 0),
    CONSTRAINT ck_snapshot_health_confirmed
        CHECK ((status = 'PERMANENT_CONFIRMED')
            = (confirmed_at IS NOT NULL AND confirmed_by_operator_user_id IS NOT NULL))
);

COMMENT ON TABLE snapshot_health IS
    'OpenAI moderation snapshot 단위 health 상태. 개별 job 실패가 아니라 synthetic target/control probe 결과로만 전이한다(INV-HLT-001).';
COMMENT ON COLUMN snapshot_health.target_only_failure_count IS
    'control probe는 성공했지만 target probe만 실패한 target-only 실패 누적 횟수. 인증·권한·결제·quota·invalid request(NON_TARGET_CLIENT_ERROR)와 UNKNOWN 분류는 이 값을 늘리지 않는다(INV-HLT-003, INV-HLT-004).';
COMMENT ON COLUMN snapshot_health.official_announcement IS
    '공급자 공식 공지 여부. 자동 수집 연동은 이 이슈 범위 밖이며 운영자가 직접 기록한다.';

-- synthetic probe 원시 결과 append-only 원장. 실사용자 요청 경로와 완전히 분리된
-- 채널이다.
CREATE TABLE snapshot_health_probe_result (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_snapshot      VARCHAR(200) NOT NULL,
    probe_type          VARCHAR(10) NOT NULL,
    classification      VARCHAR(30),
    probed_at           TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_snapshot_health_probe_result_snapshot
        FOREIGN KEY (model_snapshot) REFERENCES snapshot_health (model_snapshot),
    CONSTRAINT ck_snapshot_health_probe_result_type
        CHECK (probe_type IN ('TARGET', 'CONTROL')),
    CONSTRAINT ck_snapshot_health_probe_result_classification
        CHECK (classification IS NULL
            OR classification IN
                ('RATE_LIMITED', 'SERVER_ERROR', 'TIMEOUT_OR_NETWORK', 'NON_TARGET_CLIENT_ERROR', 'UNKNOWN'))
);

CREATE INDEX snapshot_health_probe_result_snapshot_idx
    ON snapshot_health_probe_result (model_snapshot, probed_at);

COMMENT ON COLUMN snapshot_health_probe_result.classification IS
    'NULL이면 probe 성공. 실패면 ModerationFailureClassification 값.';

-- emergency migration 감사 이력. 원본 release·대상 release·snapshot·operator를
-- append-only로 남겨 lineage를 보존한다. filter_job.filter_release_id 자체는
-- 이관 후 대상 release를 가리키도록 바뀌므로, "원래 어디서 왔는지"는 이 테이블만이
-- 담당한다.
CREATE TABLE snapshot_emergency_migration_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_snapshot          VARCHAR(200) NOT NULL,
    source_release_id       BIGINT NOT NULL,
    target_release_id       BIGINT NOT NULL,
    migrated_job_count      INT NOT NULL,
    operator_user_id        BIGINT NOT NULL,
    occurred_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_snapshot_emergency_migration_history_snapshot
        FOREIGN KEY (model_snapshot) REFERENCES snapshot_health (model_snapshot),
    CONSTRAINT fk_snapshot_emergency_migration_history_source_release
        FOREIGN KEY (source_release_id) REFERENCES filter_release (id),
    CONSTRAINT fk_snapshot_emergency_migration_history_target_release
        FOREIGN KEY (target_release_id) REFERENCES filter_release (id),
    CONSTRAINT ck_snapshot_emergency_migration_history_job_count
        CHECK (migrated_job_count >= 0),
    CONSTRAINT ck_snapshot_emergency_migration_history_different_release
        CHECK (source_release_id <> target_release_id)
);

CREATE INDEX snapshot_emergency_migration_history_snapshot_idx
    ON snapshot_emergency_migration_history (model_snapshot);

COMMENT ON COLUMN snapshot_emergency_migration_history.operator_user_id IS
    '이관을 실행한 운영자의 user_account.id. filtering 시스템은 다른 도메인 테이블을 FK로 참조하지 않는다는 #103의 경계를 여기서도 지킨다.';
