-- #110: 수동 검토 case의 우선순위(band·FIFO·aging)와 자동/수동 authority 계약.
--
-- manual_review_case는 #108이 실행 경로(AnswerModerationExecutionWorker의 소진
-- 처리)를 갖췄지만, 그 worker는 #113 production gate 전까지 어떤 스케줄러에서도
-- 호출되지 않으므로 실제 배포 환경에는 아직 행이 없다는 전제로 신규 컬럼에
-- 기존 행 보정 없이 NOT NULL을 추가한다(V14의 filter_job.logical_attempt_count와
-- 동일한 논리).
ALTER TABLE manual_review_case
    ADD COLUMN status                        VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN filter_job_id                 BIGINT NOT NULL,
    ADD COLUMN band                          VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    ADD COLUMN validated_report_signal_count INT NOT NULL DEFAULT 0,
    ADD COLUMN priority_policy_version       VARCHAR(50) NOT NULL,
    ADD COLUMN priority_reason_code          VARCHAR(30) NOT NULL DEFAULT 'DEFAULT',
    ADD COLUMN resolved_at                   TIMESTAMPTZ,
    ADD COLUMN resolved_by_operator_user_id  BIGINT,
    ADD COLUMN resolved_verdict              VARCHAR(10);

ALTER TABLE manual_review_case
    ADD CONSTRAINT fk_manual_review_case_job
        FOREIGN KEY (filter_job_id) REFERENCES filter_job (id),
    ADD CONSTRAINT ck_manual_review_case_status
        CHECK (status IN ('OPEN', 'RESOLVED')),
    ADD CONSTRAINT ck_manual_review_case_band
        CHECK (band IN ('HIGH', 'STANDARD')),
    ADD CONSTRAINT ck_manual_review_case_report_signal_count
        CHECK (validated_report_signal_count >= 0),
    ADD CONSTRAINT ck_manual_review_case_resolved_verdict
        CHECK (resolved_verdict IS NULL OR resolved_verdict IN ('ALLOW', 'BLOCK')),
    ADD CONSTRAINT ck_manual_review_case_resolved_fields
        CHECK ((status = 'RESOLVED')
            = (resolved_at IS NOT NULL AND resolved_by_operator_user_id IS NOT NULL
                AND resolved_verdict IS NOT NULL));

-- 검토자 큐 조회(effectiveBand 내림차순 + band 내 created_at FIFO)가 훑는 인덱스.
-- RESOLVED case는 큐에 나타나지 않으므로 OPEN만 부분 인덱스로 좁힌다.
CREATE INDEX manual_review_case_queue_idx
    ON manual_review_case (band, created_at)
    WHERE status = 'OPEN';

COMMENT ON COLUMN manual_review_case.filter_job_id IS
    'case가 열린 시점의 FilterJob. target+filter_release_id 조합의 모호성 없이 case가 어느 job에서 열렸는지 직접 가리킨다.';
COMMENT ON COLUMN manual_review_case.band IS
    'HIGH 또는 STANDARD 2단계만 둔다. aging 승격은 조회 시점에 계산하며 이 컬럼을 갱신하지 않는다 — 저장된 값은 report signal 평가 결과만 반영한다.';
COMMENT ON COLUMN manual_review_case.priority_reason_code IS
    'REPORT_SIGNAL(threshold 충족) 또는 DEFAULT, 또는 평가 실패 시 CALCULATION_FAILED(INV-MAN-009 fallback).';

-- priority 재평가 이력. case open과 명시적 재평가(report signal 갱신)마다 한
-- 행씩 append-only로 남긴다. manual_review_case.band/priority_reason_code는
-- "현재" 값만 담고, 이 테이블이 "언제 왜 바뀌었는지"의 전체 이력을 담당한다.
CREATE TABLE manual_review_priority_evaluation (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manual_review_case_id  BIGINT NOT NULL,
    band                   VARCHAR(20) NOT NULL,
    reason_code            VARCHAR(30) NOT NULL,
    policy_version         VARCHAR(50) NOT NULL,
    evaluated_at           TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_manual_review_priority_evaluation_case
        FOREIGN KEY (manual_review_case_id) REFERENCES manual_review_case (id),
    CONSTRAINT ck_manual_review_priority_evaluation_band
        CHECK (band IN ('HIGH', 'STANDARD'))
);

CREATE INDEX manual_review_priority_evaluation_case_idx
    ON manual_review_priority_evaluation (manual_review_case_id);

COMMENT ON TABLE manual_review_priority_evaluation IS
    'priority 평가 append-only 감사 이력(재평가 이력). manual_review_case 유일성(INV-MAN-001)과 무관하게 case당 여러 행을 가질 수 있다.';
