-- #111: manual review case 생성을 관리자 채널(Slack)에 알리는 전용
-- outbox 성격의 테이블이다. 기존 outbox_event와 무관한 별도 테이블로 둬서,
-- case_id·admin_link_path만 컴럼으로 노출해 허용목록을 스키마 수준에서
-- 강제한다(INV-SLK-003, INV-SLK-004). case_id UNIQUE 제약이 생성 시점
-- 중복 발행을 막는다(INV-SLK-005).
CREATE TABLE notification_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id             BIGINT NOT NULL,
    admin_link_path     VARCHAR(255) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    next_attempt_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    processed_at        TIMESTAMPTZ,
    lease_owner         VARCHAR(100),
    lease_expires_at    TIMESTAMPTZ,
    lease_generation    BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uq_notification_event_case_id
        UNIQUE (case_id),
    CONSTRAINT fk_notification_event_case
        FOREIGN KEY (case_id) REFERENCES manual_review_case (id),
    CONSTRAINT ck_notification_event_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'DEAD')),
    CONSTRAINT ck_notification_event_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_notification_event_processed_at
        CHECK (
            (status = 'PROCESSED') = (processed_at IS NOT NULL)
            AND (processed_at IS NULL OR processed_at >= created_at)
        ),
    CONSTRAINT ck_notification_event_lease_generation
        CHECK (lease_generation >= 0),
    CONSTRAINT ck_notification_event_lease_state
        CHECK (
            (status = 'PROCESSING') = (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
            AND (lease_owner IS NULL) = (lease_expires_at IS NULL)
        )
);

CREATE INDEX notification_event_claim_idx
    ON notification_event (status, next_attempt_at, lease_expires_at, id)
    WHERE status IN ('PENDING', 'FAILED', 'PROCESSING');
