-- #153: 신고 기능이 의존하는 사건(case)·증거 스냅샷·감사 이력의 정합성 기반.
--
-- report_case는 대상 콘텐츠(사용자/질문글/답변)당 열린 사건을 최대 하나로
-- 제한한다(INV-RPT-001) — 뒤의 부분 유일 인덱스 3개가 실제 강제를 담당한다.
-- severity/queue는 이 이슈에서 항상 NORMAL/STANDARD로 생성되고, 실제 산출
-- 로직은 #156이 담당한다.
CREATE TABLE report_case (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id          BIGINT,
    direction_post_id       BIGINT,
    answer_id               BIGINT,
    status                  VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    severity                VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    queue                   VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    decision                VARCHAR(30),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    resolved_at             TIMESTAMPTZ,

    CONSTRAINT fk_report_case_target_user
        FOREIGN KEY (target_user_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_case_direction_post
        FOREIGN KEY (direction_post_id) REFERENCES direction_post (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_case_answer
        FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE RESTRICT,
    CONSTRAINT ck_report_case_exactly_one_target
        CHECK (num_nonnulls(target_user_id, direction_post_id, answer_id) = 1),
    CONSTRAINT ck_report_case_status
        CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED')),
    CONSTRAINT ck_report_case_severity
        CHECK (severity IN ('NORMAL', 'CRITICAL')),
    CONSTRAINT ck_report_case_queue
        CHECK (queue IN ('STANDARD', 'URGENT')),
    CONSTRAINT ck_report_case_decision
        CHECK (decision IS NULL OR decision IN ('ACTIONED', 'NO_VIOLATION', 'MORE_INFO_REQUIRED')),
    CONSTRAINT ck_report_case_resolution
        CHECK (
            (status = 'RESOLVED') = (decision IS NOT NULL AND resolved_at IS NOT NULL)
            AND (resolved_at IS NULL OR resolved_at >= created_at)
        )
);

COMMENT ON TABLE report_case IS
    '대상 콘텐츠당 열린 사건은 최대 하나(INV-RPT-001). 여러 신고자의 제보를 하나로 묶는 처리 단위.';

-- 신고 시점 증거의 비정규화 사본. author_id에 FK를 걸지 않는다 — 계정 삭제와
-- 증거 보존이 충돌하면 증거가 이긴다(설계 문서 §7). target_id·target_type도
-- FK 없이 opaque하게 보관한다 — 원본이 하드 삭제되거나 편집돼도 신고 시점
-- 내용은 그대로 남아야 한다.
CREATE TABLE report_content_snapshot (
    report_id               BIGINT PRIMARY KEY,
    captured_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    target_type             VARCHAR(20) NOT NULL,
    target_id                BIGINT NOT NULL,
    author_id               BIGINT NOT NULL,
    body_text                TEXT,
    media_object_keys       TEXT[] NOT NULL DEFAULT '{}',
    edit_count               INTEGER NOT NULL DEFAULT 0,
    content_published_at    TIMESTAMPTZ,
    content_hash             CHAR(64) NOT NULL,
    legal_hold               BOOLEAN NOT NULL DEFAULT FALSE,
    purge_after              TIMESTAMPTZ,

    CONSTRAINT fk_report_content_snapshot_report
        FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE RESTRICT,
    CONSTRAINT ck_report_content_snapshot_target_type
        CHECK (target_type IN ('USER', 'DIRECTION_POST', 'ANSWER')),
    CONSTRAINT ck_report_content_snapshot_target_id
        CHECK (target_id > 0),
    CONSTRAINT ck_report_content_snapshot_author_id
        CHECK (author_id > 0),
    CONSTRAINT ck_report_content_snapshot_edit_count
        CHECK (edit_count >= 0)
);

COMMENT ON TABLE report_content_snapshot IS
    '신고 시점의 본문·미디어·해시를 보관하는 append-only 증거. UPDATE·DELETE는 트리거가 거부한다(INV-RPT-004).';
COMMENT ON COLUMN report_content_snapshot.content_hash IS
    '정렬된 media_object_keys와 body_text로 계산한 SHA-256 해시. #154의 재신고 중복 억제 판정에 쓰인다.';

-- 사건 append-only 이력. 이 이슈가 실제로 만드는 이벤트는 CASE_OPENED뿐이고
-- 나머지 종류는 #154(REPORT_ATTACHED/DUPLICATE_SUPPRESSED)·#156(ESCALATED/
-- MORE_INFO_REQUESTED/RESOLVED)이 발행한다.
CREATE TABLE report_case_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                 BIGINT NOT NULL,
    event_type              VARCHAR(30) NOT NULL,
    detail                  TEXT,
    occurred_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_report_case_event_case
        FOREIGN KEY (case_id) REFERENCES report_case (id) ON DELETE RESTRICT,
    CONSTRAINT ck_report_case_event_type
        CHECK (event_type IN (
            'CASE_OPENED', 'REPORT_ATTACHED', 'DUPLICATE_SUPPRESSED',
            'ESCALATED', 'MORE_INFO_REQUESTED', 'RESOLVED'
        ))
);

CREATE INDEX report_case_event_case_idx
    ON report_case_event (case_id, occurred_at);

COMMENT ON TABLE report_case_event IS
    '사건 append-only 이력. UPDATE·DELETE는 트리거가 거부한다(INV-RPT-004).';

-- report_case당 대상별 부분 유일 인덱스. INV-RPT-001의 실제 강제.
CREATE UNIQUE INDEX uq_open_case_user
    ON report_case (target_user_id)
    WHERE target_user_id IS NOT NULL AND status IN ('OPEN', 'UNDER_REVIEW');

CREATE UNIQUE INDEX uq_open_case_post
    ON report_case (direction_post_id)
    WHERE direction_post_id IS NOT NULL AND status IN ('OPEN', 'UNDER_REVIEW');

CREATE UNIQUE INDEX uq_open_case_answer
    ON report_case (answer_id)
    WHERE answer_id IS NOT NULL AND status IN ('OPEN', 'UNDER_REVIEW');

-- report_content_snapshot과 report_case_event는 생성된 뒤 절대 바뀌지 않는다.
-- enforce_question_text_immutability()는 특정 컬럼의 UPDATE만 막는 반면, 신고
-- 증거는 UPDATE와 DELETE 둘 다 막아야 한다(설계 문서 §7).
CREATE FUNCTION enforce_report_evidence_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only and cannot be updated or deleted', TG_TABLE_NAME
        USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER tr_report_content_snapshot_immutable
BEFORE UPDATE OR DELETE ON report_content_snapshot
FOR EACH ROW EXECUTE FUNCTION enforce_report_evidence_immutability();

CREATE TRIGGER tr_report_case_event_immutable
BEFORE UPDATE OR DELETE ON report_case_event
FOR EACH ROW EXECUTE FUNCTION enforce_report_evidence_immutability();

-- report 확장: 사건 연결과 하위 사유, 사유 코드 8종 catalog 고정.
ALTER TABLE report
    ADD COLUMN case_id BIGINT REFERENCES report_case (id) ON DELETE RESTRICT,
    ADD COLUMN sub_reason_code VARCHAR(30);

ALTER TABLE report DROP CONSTRAINT ck_report_reason;
ALTER TABLE report ADD CONSTRAINT ck_report_reason
    CHECK (reason_code IN (
        'SEXUAL_CONTENT', 'VIOLENCE_OR_THREAT', 'HATE_OR_HARASSMENT', 'PRIVACY_VIOLATION',
        'SPAM_OR_ADVERTISING', 'IMPERSONATION', 'ILLEGAL_OR_DANGEROUS', 'OTHER'
    ));

ALTER TABLE report ADD CONSTRAINT ck_report_sub_reason
    CHECK (
        sub_reason_code IS NULL
        OR (reason_code = 'SEXUAL_CONTENT' AND sub_reason_code IN ('CSAM', 'NCII'))
        OR (reason_code = 'VIOLENCE_OR_THREAT' AND sub_reason_code = 'CREDIBLE_THREAT')
    );

COMMENT ON COLUMN report.sub_reason_code IS
    '즉시 대응이 필요한 신고의 하위 사유. 허용 조합은 ck_report_sub_reason이 강제한다.';

-- MORE_INFO_REQUIRED는 종결이 아니므로(설계 문서 §6.3) 열린 상태 술어에
-- 포함해야 같은 신고자의 중복 신고 차단이 유지된다(INV-RPT-002). 수정 전에는
-- 운영자가 추가 정보를 요청하는 순간 이 차단이 풀렸다.
DROP INDEX uq_open_report_user;
CREATE UNIQUE INDEX uq_open_report_user
    ON report (reporter_id, target_user_id)
    WHERE target_user_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW', 'MORE_INFO_REQUIRED');

DROP INDEX uq_open_report_post;
CREATE UNIQUE INDEX uq_open_report_post
    ON report (reporter_id, direction_post_id)
    WHERE direction_post_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW', 'MORE_INFO_REQUIRED');

DROP INDEX uq_open_report_answer;
CREATE UNIQUE INDEX uq_open_report_answer
    ON report (reporter_id, answer_id)
    WHERE answer_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW', 'MORE_INFO_REQUIRED');

-- notification이 신고 처리 결과를 가리킬 수 있게 대상 컬럼을 넓힌다. "최대
-- 1개 대상" 불변식은 유지한다.
ALTER TABLE notification ADD COLUMN report_id BIGINT REFERENCES report (id) ON DELETE SET NULL;

ALTER TABLE notification DROP CONSTRAINT ck_notification_target;
ALTER TABLE notification ADD CONSTRAINT ck_notification_target
    CHECK (num_nonnulls(direction_post_id, answer_id, report_id) <= 1);
