-- 방향으로 연결되는 소통 — 선택 테이블 기준 전체 DDL
-- Target: PostgreSQL 16+ / PostGIS 3+
--
-- 이 파일은 001~004 뒤에 이어서 실행하는 증분 마이그레이션이 아니다.
-- 사용자가 확정한 ERD 테이블 목록을 기준으로 다시 작성한 독립 실행형 기준 DDL이다.
-- 빈 스키마에서 이 파일만 실행하며, 001~004와 같은 스키마에 함께 실행하지 않는다.
--
-- 스키마의 기준(source of truth)은 docs/dbml/direction_communication.dbml이다.
-- 이 파일은 거기서 파생하며, 스키마를 바꿀 때는 DBML을 먼저 고친다.
--
-- ERD 내 상태값 표와 CopyOf* 표는 데이터 테이블이 아니라 값 목록으로 해석해
-- 각 도메인 컬럼의 CHECK 제약으로 옮겼다. 한글 설명형 컬럼명, DEFAULT AS,
-- 이름 없는 ENUM, 타입이 맞지 않는 FK는 PostgreSQL 실행 가능한 이름과 타입으로 교정했다.
--
-- 정책상 숫자 기본값을 두지 않는 항목:
--   * 방향 글의 최소·최대 거리(P02)
--   * 발송당 최초·최대 수신자 수(P03, 애플리케이션 선정 정책)
--   * 방향 글 만료 기간(P04, expires_at 자체는 필수)
--   * 질문 배정 주기와 한 주기당 개수(P15)
--
-- P06 위치 정책(2026-08-03 확정: 1안)
--   짧은 TTL의 정확 좌표를 active_user_presence에 저장하고 외부에는 흐린 값만 제공한다.
--   active_user_presence.position과 post_audience.origin_position은 실제 사용자 좌표를
--   담는 운영 컬럼이며 더 이상 합성 데이터 전용이 아니다. 정확 좌표는 API 응답, 로그,
--   분석 이벤트, Outbox payload에 넣지 않는다. 보존 기간은 P07에서 확정한다.
--
-- P10 연령 정책 승인 전에는 user_private_attribute.age_band를 수집하지 않는다.
--
-- 2026-08-03 스키마 변경
--   1. post_media + answer_media를 media_attachment 한 테이블로 통합했다. media_id를 PK로
--      두어 "한 미디어는 한 콘텐츠에만" 불변식이 트리거 없이 원자적으로 성립한다. 기존
--      count 기반 constraint trigger 2종은 서로의 미커밋 행을 볼 수 없는 두 트랜잭션이
--      같은 미디어를 각각 다른 콘텐츠에 붙일 때 둘 다 통과하는 구멍이 있어 제거했다.
--   2. FK 컬럼 인덱스를 일괄 추가했다. PostgreSQL은 FK에 인덱스를 자동 생성하지 않는다.
--   3. direction_scheme에 status = 'ACTIVE' partial unique를 추가해 같은 code의 두 버전이
--      동시에 ACTIVE가 되는 것을 막았다.
--   4. post_recipient에 상태와 타임스탬프를 묶는 CHECK와 용량 해제 constraint trigger를
--      추가했다. 이 테이블만 상태 대응 제약이 없어 status = 'SKIPPED'인데 skipped_at이
--      비어 있는 행이 허용됐다.

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

-- -----------------------------------------------------------------------------
-- 1. 지역과 계정
-- -----------------------------------------------------------------------------

CREATE TABLE region_code (
    code                    VARCHAR(100) PRIMARY KEY,
    parent_code             VARCHAR(100),
    display_name            TEXT NOT NULL,
    level                   VARCHAR(20) NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_region_code_parent
        FOREIGN KEY (parent_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT ck_region_code_not_self_parent
        CHECK (parent_code IS NULL OR parent_code <> code),
    CONSTRAINT ck_region_code_display_name
        CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_region_code_level
        CHECK (level IN ('COUNTRY', 'REGION', 'CITY', 'DISTRICT')),
    CONSTRAINT ck_region_code_root
        CHECK ((level = 'COUNTRY') = (parent_code IS NULL))
);

COMMENT ON COLUMN region_code.parent_code IS
    '상위 지역 코드. 두 단계 이상의 순환은 지역 코드 적재 트랜잭션에서 차단한다.';

CREATE TABLE user_account (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role                    VARCHAR(20) NOT NULL DEFAULT 'USER',
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    coarse_region_code      VARCHAR(100) NOT NULL,
    locale                  VARCHAR(35) NOT NULL,
    timezone                VARCHAR(64) NOT NULL,
    nickname                VARCHAR(50),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_user_account_region
        FOREIGN KEY (coarse_region_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT ck_user_account_role
        CHECK (role IN ('USER', 'OPERATOR')),
    CONSTRAINT ck_user_account_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'DELETED')),
    CONSTRAINT ck_user_account_nickname
        CHECK (nickname IS NULL OR btrim(nickname) <> ''),
    CONSTRAINT ck_user_account_deleted_at
        CHECK (
            (status = 'DELETED' AND deleted_at IS NOT NULL)
            OR (status <> 'DELETED' AND deleted_at IS NULL)
        )
);

CREATE TABLE user_private_attribute (
    user_id                 BIGINT PRIMARY KEY,
    gender                  VARCHAR(20),
    age_band                VARCHAR(20),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_user_private_attribute_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_private_attribute_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED')),
    CONSTRAINT ck_user_private_attribute_age_band
        CHECK (age_band IS NULL OR age_band IN (
            '10S', '20S', '30S', '40S', '50S', '60S', '70S_PLUS'
        ))
);

COMMENT ON TABLE user_private_attribute IS
    '선택형 민감 속성. P10 승인 전 age_band를 실제 사용자에게 수집하지 않는다.';

CREATE TABLE active_user_presence (
    user_id                 BIGINT PRIMARY KEY,
    position                geography(Point, 4326),
    coarse_cell_id          VARCHAR(100),
    coarse_region_code      VARCHAR(100) NOT NULL,
    accuracy_m              NUMERIC(10, 2),
    receive_allowed         BOOLEAN NOT NULL DEFAULT FALSE,
    location_at             TIMESTAMPTZ NOT NULL,
    expires_at              TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_active_user_presence_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_active_user_presence_region
        FOREIGN KEY (coarse_region_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT ck_active_user_presence_location
        CHECK (num_nonnulls(position, coarse_cell_id) >= 1),
    CONSTRAINT ck_active_user_presence_accuracy
        CHECK (accuracy_m IS NULL OR accuracy_m >= 0),
    CONSTRAINT ck_active_user_presence_expiry
        CHECK (expires_at > location_at)
);

COMMENT ON TABLE active_user_presence IS
    '수신 후보 탐색용 TTL 읽기 모델. 위치 측정 시각과 만료 시각으로 현재성을 판단한다. '
    'P06 1안에 따라 서비스 전체에서 정확 좌표를 보관하는 유일한 곳이며 접근을 매칭 워커로 제한한다.';
COMMENT ON COLUMN active_user_presence.position IS
    'P06 1안 확정에 따라 실제 사용자 좌표를 담는 운영 컬럼. 거리·방위 계산에만 사용하고 '
    'API 응답, 로그, 분석 이벤트, Outbox payload에는 넣지 않는다.';
COMMENT ON COLUMN active_user_presence.coarse_cell_id IS
    '정확 좌표를 대체하지 않고 보조로 두는 공간 셀 식별자. P06 2안을 채택하지 않아 선택 입력이다.';

CREATE TABLE recipient_receive_state (
    user_id                     BIGINT PRIMARY KEY,
    active_unhandled_count      SMALLINT NOT NULL DEFAULT 0,
    recent_received_count       INTEGER NOT NULL DEFAULT 0,
    recent_window_started_at    TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    last_received_at            TIMESTAMPTZ,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_recipient_receive_state_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_recipient_receive_state_active_count
        CHECK (active_unhandled_count BETWEEN 0 AND 5),
    CONSTRAINT ck_recipient_receive_state_recent_count
        CHECK (recent_received_count >= 0),
    CONSTRAINT ck_recipient_receive_state_last_received
        CHECK (last_received_at IS NULL OR last_received_at >= recent_window_started_at)
);

COMMENT ON TABLE recipient_receive_state IS
    '활성 미처리 방향 글 5개 상한을 동시성 아래에서 예약하기 위한 사용자별 투영값.';

-- -----------------------------------------------------------------------------
-- 2. 질문 제안, 검토, 승인 질문과 배정
-- -----------------------------------------------------------------------------

CREATE TABLE question_proposal (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposer_id             BIGINT NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    proposed_text           TEXT NOT NULL,
    decision_reason         TEXT,
    submitted_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_question_proposal_proposer
        FOREIGN KEY (proposer_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT ck_question_proposal_status
        CHECK (status IN (
            'DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED'
        )),
    CONSTRAINT ck_question_proposal_text
        CHECK (btrim(proposed_text) <> ''),
    CONSTRAINT ck_question_proposal_submission
        CHECK (status = 'DRAFT' OR submitted_at IS NOT NULL)
);

CREATE TABLE question_proposal_review (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id             BIGINT NOT NULL,
    reviewer_id             BIGINT NOT NULL,
    decision                VARCHAR(30) NOT NULL,
    reason                  TEXT,
    reviewed_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_question_proposal_review_proposal
        FOREIGN KEY (proposal_id) REFERENCES question_proposal (id) ON DELETE RESTRICT,
    CONSTRAINT fk_question_proposal_review_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT ck_question_proposal_review_decision
        CHECK (decision IN ('APPROVED', 'REJECTED')),
    CONSTRAINT ck_question_proposal_review_reason
        CHECK (decision = 'APPROVED' OR NULLIF(btrim(reason), '') IS NOT NULL)
);

CREATE TABLE approved_question (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_proposal_id      BIGINT,
    source_type             VARCHAR(30) NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    question_text           TEXT NOT NULL,
    answer_format           VARCHAR(20) NOT NULL,
    active_from             TIMESTAMPTZ,
    active_until            TIMESTAMPTZ,
    approved_at             TIMESTAMPTZ,
    approved_by             BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_approved_question_source_proposal
        FOREIGN KEY (source_proposal_id) REFERENCES question_proposal (id) ON DELETE RESTRICT,
    CONSTRAINT fk_approved_question_approver
        FOREIGN KEY (approved_by) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT uq_approved_question_source_proposal
        UNIQUE (source_proposal_id),
    CONSTRAINT ck_approved_question_source_type
        CHECK (source_type IN ('OPERATOR', 'USER_PROPOSAL', 'GENERATED_CANDIDATE')),
    CONSTRAINT ck_approved_question_source
        CHECK (
            (source_type = 'USER_PROPOSAL' AND source_proposal_id IS NOT NULL)
            OR (source_type <> 'USER_PROPOSAL' AND source_proposal_id IS NULL)
        ),
    CONSTRAINT ck_approved_question_status
        CHECK (status IN ('PENDING_REVIEW', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_approved_question_text
        CHECK (btrim(question_text) <> ''),
    CONSTRAINT ck_approved_question_answer_format
        CHECK (answer_format IN ('PHOTO', 'TEXT', 'BOTH')),
    CONSTRAINT ck_approved_question_active_range
        CHECK (active_until IS NULL OR active_from IS NULL OR active_until > active_from),
    CONSTRAINT ck_approved_question_approval
        CHECK (
            status <> 'ACTIVE'
            OR (approved_at IS NOT NULL AND approved_by IS NOT NULL AND active_from IS NOT NULL)
        )
);

COMMENT ON TABLE approved_question IS
    '검토를 통과해 배정과 발송에 사용할 수 있는 불변 질문 문구.';

CREATE TABLE question_assignment_cycle (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    cycle_key               VARCHAR(100) NOT NULL,
    pool_version            VARCHAR(100) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    starts_at               TIMESTAMPTZ NOT NULL,
    ends_at                 TIMESTAMPTZ NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_question_assignment_cycle_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT uq_question_assignment_cycle_user_key
        UNIQUE (user_id, cycle_key),
    CONSTRAINT ck_question_assignment_cycle_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_question_assignment_cycle_range
        CHECK (ends_at > starts_at)
);

CREATE TABLE question_assignment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id                BIGINT NOT NULL,
    approved_question_id    BIGINT NOT NULL,
    display_order           INTEGER NOT NULL,
    assigned_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    first_viewed_at         TIMESTAMPTZ,
    used_at                 TIMESTAMPTZ,

    CONSTRAINT fk_question_assignment_cycle
        FOREIGN KEY (cycle_id) REFERENCES question_assignment_cycle (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_assignment_question
        FOREIGN KEY (approved_question_id) REFERENCES approved_question (id) ON DELETE RESTRICT,
    CONSTRAINT uq_question_assignment_cycle_question
        UNIQUE (cycle_id, approved_question_id),
    CONSTRAINT uq_question_assignment_cycle_order
        UNIQUE (cycle_id, display_order),
    CONSTRAINT ck_question_assignment_display_order
        CHECK (display_order > 0),
    CONSTRAINT ck_question_assignment_viewed_at
        CHECK (first_viewed_at IS NULL OR first_viewed_at >= assigned_at),
    CONSTRAINT ck_question_assignment_used_at
        CHECK (used_at IS NULL OR used_at >= assigned_at)
);

-- -----------------------------------------------------------------------------
-- 3. 방향 정책, 방향 글, 수신 권한, 답변과 미디어
-- -----------------------------------------------------------------------------

CREATE TABLE direction_scheme (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(50) NOT NULL,
    version                 INTEGER NOT NULL,
    type                    VARCHAR(30) NOT NULL,
    segment_count           INTEGER,
    start_offset_deg        NUMERIC(7, 3) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uq_direction_scheme_code_version
        UNIQUE (code, version),
    CONSTRAINT ck_direction_scheme_version
        CHECK (version > 0),
    CONSTRAINT ck_direction_scheme_type
        CHECK (type IN ('EQUAL_SEGMENTS', 'CONTINUOUS')),
    CONSTRAINT ck_direction_scheme_segment_count
        CHECK (
            (type = 'EQUAL_SEGMENTS' AND segment_count > 0)
            OR (type = 'CONTINUOUS' AND segment_count IS NULL)
        ),
    CONSTRAINT ck_direction_scheme_start_offset
        CHECK (start_offset_deg >= 0 AND start_offset_deg < 360),
    CONSTRAINT ck_direction_scheme_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE TABLE direction_segment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id               BIGINT NOT NULL,
    segment_key             VARCHAR(20) NOT NULL,
    display_name            VARCHAR(50) NOT NULL,
    center_bearing_deg      NUMERIC(7, 3) NOT NULL,
    angular_width_deg       NUMERIC(7, 3) NOT NULL,
    sort_order              INTEGER NOT NULL,

    CONSTRAINT fk_direction_segment_scheme
        FOREIGN KEY (scheme_id) REFERENCES direction_scheme (id) ON DELETE RESTRICT,
    CONSTRAINT uq_direction_segment_key
        UNIQUE (scheme_id, segment_key),
    CONSTRAINT uq_direction_segment_order
        UNIQUE (scheme_id, sort_order),
    CONSTRAINT ck_direction_segment_center
        CHECK (center_bearing_deg >= 0 AND center_bearing_deg < 360),
    CONSTRAINT ck_direction_segment_width
        CHECK (angular_width_deg > 0 AND angular_width_deg <= 360),
    CONSTRAINT ck_direction_segment_order
        CHECK (sort_order >= 0)
);

CREATE TABLE media_asset (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id                BIGINT NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'UPLOADING',
    storage_key             VARCHAR(500) NOT NULL,
    mime_type               VARCHAR(100) NOT NULL,
    byte_size               BIGINT NOT NULL,
    checksum                VARCHAR(128) NOT NULL,
    exif_stripped           BOOLEAN NOT NULL DEFAULT FALSE,
    moderation_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_media_asset_owner
        FOREIGN KEY (owner_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT uq_media_asset_id_owner
        UNIQUE (id, owner_id),
    CONSTRAINT uq_media_asset_storage_key
        UNIQUE (storage_key),
    CONSTRAINT ck_media_asset_status
        CHECK (status IN ('UPLOADING', 'READY', 'REJECTED', 'DELETED')),
    CONSTRAINT ck_media_asset_moderation
        CHECK (moderation_status IN ('PENDING', 'PASSED', 'REVIEW_HELD', 'REJECTED')),
    CONSTRAINT ck_media_asset_size
        CHECK (byte_size > 0),
    CONSTRAINT ck_media_asset_deleted_at
        CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL))
);

CREATE TABLE direction_post (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id               BIGINT NOT NULL,
    approved_question_id    BIGINT NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    idempotency_key         VARCHAR(200) NOT NULL,
    body_text               TEXT,
    coarse_region_code      VARCHAR(100) NOT NULL,
    moderation_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    submitted_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    published_at            TIMESTAMPTZ,
    expires_at              TIMESTAMPTZ NOT NULL,
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_direction_post_sender
        FOREIGN KEY (sender_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_direction_post_question
        FOREIGN KEY (approved_question_id) REFERENCES approved_question (id) ON DELETE RESTRICT,
    CONSTRAINT fk_direction_post_region
        FOREIGN KEY (coarse_region_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT uq_direction_post_idempotency
        UNIQUE (sender_id, idempotency_key),
    CONSTRAINT uq_direction_post_id_sender
        UNIQUE (id, sender_id),
    CONSTRAINT ck_direction_post_status
        CHECK (status IN (
            'SUBMITTED', 'SAFETY_CHECKING', 'MATCHING', 'ACTIVE', 'MATCH_FAILED',
            'REVIEW_HELD', 'REJECTED', 'EXPIRED', 'HIDDEN', 'DELETED'
        )),
    CONSTRAINT ck_direction_post_moderation
        CHECK (moderation_status IN ('PENDING', 'PASSED', 'REVIEW_HELD', 'REJECTED')),
    CONSTRAINT ck_direction_post_body
        CHECK (body_text IS NULL OR btrim(body_text) <> ''),
    CONSTRAINT ck_direction_post_expiry
        CHECK (expires_at > submitted_at),
    CONSTRAINT ck_direction_post_published_at
        CHECK (status <> 'ACTIVE' OR published_at IS NOT NULL),
    CONSTRAINT ck_direction_post_deleted_at
        CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL))
);

CREATE TABLE post_audience (
    post_id                     BIGINT PRIMARY KEY,
    direction_scheme_id         BIGINT NOT NULL,
    selected_segment_key        VARCHAR(20) NOT NULL,
    center_bearing_deg          NUMERIC(7, 3) NOT NULL,
    angular_width_deg           NUMERIC(7, 3) NOT NULL,
    min_distance_m              BIGINT NOT NULL,
    max_distance_m              BIGINT NOT NULL,
    origin_position             geography(Point, 4326),
    origin_cell_id              VARCHAR(100),
    snapshotted_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_post_audience_post
        FOREIGN KEY (post_id) REFERENCES direction_post (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_audience_segment
        FOREIGN KEY (direction_scheme_id, selected_segment_key)
        REFERENCES direction_segment (scheme_id, segment_key) ON DELETE RESTRICT,
    CONSTRAINT ck_post_audience_center
        CHECK (center_bearing_deg >= 0 AND center_bearing_deg < 360),
    CONSTRAINT ck_post_audience_width
        CHECK (angular_width_deg > 0 AND angular_width_deg <= 360),
    CONSTRAINT ck_post_audience_distance
        CHECK (min_distance_m >= 0 AND max_distance_m > min_distance_m),
    CONSTRAINT ck_post_audience_origin
        CHECK (num_nonnulls(origin_position, origin_cell_id) >= 1)
);

COMMENT ON COLUMN post_audience.origin_position IS
    'P06 1안 확정에 따라 실제 발송 원점 좌표를 담는 운영 컬럼. 외부 응답에는 노출하지 않는다.';

CREATE TABLE post_recipient (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id                 BIGINT NOT NULL,
    recipient_id            BIGINT NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    distance_band           VARCHAR(50) NOT NULL,
    matched_bearing_deg     NUMERIC(7, 3) NOT NULL,
    matched_region_code     VARCHAR(100) NOT NULL,
    matched_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    discovered_at           TIMESTAMPTZ,
    opened_at               TIMESTAMPTZ,
    skipped_at              TIMESTAMPTZ,
    capacity_released_at    TIMESTAMPTZ,
    expired_at              TIMESTAMPTZ,
    blocked_at              TIMESTAMPTZ,

    CONSTRAINT fk_post_recipient_post
        FOREIGN KEY (post_id) REFERENCES direction_post (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_recipient_user
        FOREIGN KEY (recipient_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_recipient_region
        FOREIGN KEY (matched_region_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT uq_post_recipient_post_user
        UNIQUE (post_id, recipient_id),
    CONSTRAINT uq_post_recipient_id_user
        UNIQUE (id, recipient_id),
    CONSTRAINT ck_post_recipient_status
        CHECK (status IN (
            'AVAILABLE', 'DISCOVERED', 'OPENED', 'ANSWERED', 'SKIPPED', 'EXPIRED', 'BLOCKED'
        )),
    CONSTRAINT ck_post_recipient_bearing
        CHECK (matched_bearing_deg >= 0 AND matched_bearing_deg < 360),
    CONSTRAINT ck_post_recipient_distance_band
        CHECK (btrim(distance_band) <> ''),
    CONSTRAINT ck_post_recipient_timestamps
        CHECK (
            (discovered_at IS NULL OR discovered_at >= matched_at)
            AND (opened_at IS NULL OR opened_at >= matched_at)
            AND (skipped_at IS NULL OR skipped_at >= matched_at)
            AND (capacity_released_at IS NULL OR capacity_released_at >= matched_at)
            AND (expired_at IS NULL OR expired_at >= matched_at)
            AND (blocked_at IS NULL OR blocked_at >= matched_at)
        ),
    -- 종결 상태는 각자의 타임스탬프와 동치여야 한다. 상태와 그 상태의 타임스탬프는
    -- T6·T6A·T6B에서 같은 UPDATE 문으로 기록하므로 즉시 검사하는 CHECK로 둔다.
    -- 용량 해제(capacity_released_at)는 별도 문장으로 조건부 갱신하므로 CHECK가 아니라
    -- 아래 ct_post_recipient_capacity_release 지연 트리거가 커밋 시점에 검사한다.
    CONSTRAINT ck_post_recipient_status_timestamps
        CHECK (
            (status = 'SKIPPED') = (skipped_at IS NOT NULL)
            AND (status = 'EXPIRED') = (expired_at IS NOT NULL)
            AND (status = 'BLOCKED') = (blocked_at IS NOT NULL)
            AND (status <> 'DISCOVERED' OR discovered_at IS NOT NULL)
            AND (status <> 'OPENED' OR opened_at IS NOT NULL)
            AND (status <> 'AVAILABLE' OR (discovered_at IS NULL AND opened_at IS NULL))
        )
);

CREATE TABLE answer (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_recipient_id       BIGINT NOT NULL,
    author_id               BIGINT NOT NULL,
    status                  VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    idempotency_key         VARCHAR(200) NOT NULL,
    body_text               TEXT,
    coarse_region_code      VARCHAR(100) NOT NULL,
    bearing_from_sender_deg NUMERIC(7, 3) NOT NULL,
    distance_band           VARCHAR(50) NOT NULL,
    moderation_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    submitted_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    published_at            TIMESTAMPTZ,
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_answer_recipient_author
        FOREIGN KEY (post_recipient_id, author_id)
        REFERENCES post_recipient (id, recipient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_answer_region
        FOREIGN KEY (coarse_region_code) REFERENCES region_code (code) ON DELETE RESTRICT,
    CONSTRAINT uq_answer_idempotency
        UNIQUE (author_id, idempotency_key),
    CONSTRAINT uq_answer_id_author
        UNIQUE (id, author_id),
    CONSTRAINT ck_answer_status
        CHECK (status IN ('SUBMITTED', 'SAFETY_CHECKING', 'PUBLISHED', 'REJECTED', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_answer_moderation
        CHECK (moderation_status IN ('PENDING', 'PASSED', 'REVIEW_HELD', 'REJECTED')),
    CONSTRAINT ck_answer_body
        CHECK (body_text IS NULL OR btrim(body_text) <> ''),
    CONSTRAINT ck_answer_bearing
        CHECK (bearing_from_sender_deg >= 0 AND bearing_from_sender_deg < 360),
    CONSTRAINT ck_answer_distance_band
        CHECK (btrim(distance_band) <> ''),
    CONSTRAINT ck_answer_published_at
        CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT ck_answer_deleted_at
        CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL))
);

-- 미디어 첨부는 방향 글과 답변을 통틀어 이 한 테이블이 담당한다.
-- media_id를 PK로 둔 것이 "한 미디어는 한 콘텐츠에만 붙는다"는 불변식 자체이므로,
-- 두 트랜잭션이 같은 미디어를 동시에 다른 콘텐츠에 붙이면 뒤늦은 쪽이 PK 충돌로 실패한다.
-- (post_id, owner_id)와 (answer_id, owner_id) 복합 FK는 MATCH SIMPLE이라 해당 대상이
-- NULL이면 검사를 건너뛰고, 값이 있을 때만 콘텐츠 작성자와 미디어 소유자의 일치를 요구한다.
CREATE TABLE media_attachment (
    media_id                BIGINT PRIMARY KEY,
    owner_id                BIGINT NOT NULL,
    post_id                 BIGINT,
    answer_id               BIGINT,
    display_order           INTEGER NOT NULL,

    CONSTRAINT fk_media_attachment_asset_owner
        FOREIGN KEY (media_id, owner_id) REFERENCES media_asset (id, owner_id) ON DELETE RESTRICT,
    CONSTRAINT fk_media_attachment_post_owner
        FOREIGN KEY (post_id, owner_id) REFERENCES direction_post (id, sender_id) ON DELETE CASCADE,
    CONSTRAINT fk_media_attachment_answer_owner
        FOREIGN KEY (answer_id, owner_id) REFERENCES answer (id, author_id) ON DELETE CASCADE,
    CONSTRAINT ck_media_attachment_exactly_one_target
        CHECK (num_nonnulls(post_id, answer_id) = 1),
    CONSTRAINT ck_media_attachment_order
        CHECK (display_order >= 0)
);

COMMENT ON TABLE media_attachment IS
    '미디어를 방향 글 또는 답변 중 정확히 하나에 연결하는 첨부 테이블. '
    'media_id PK가 단일 첨부 불변식을 원자적으로 강제한다.';

CREATE UNIQUE INDEX uq_media_attachment_post_order
    ON media_attachment (post_id, display_order) WHERE post_id IS NOT NULL;

CREATE UNIQUE INDEX uq_media_attachment_answer_order
    ON media_attachment (answer_id, display_order) WHERE answer_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 4. 차단, 신고와 운영 검토
-- -----------------------------------------------------------------------------

CREATE TABLE user_block (
    blocker_id              BIGINT NOT NULL,
    blocked_id              BIGINT NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    released_at             TIMESTAMPTZ,

    CONSTRAINT pk_user_block
        PRIMARY KEY (blocker_id, blocked_id),
    CONSTRAINT fk_user_block_blocker
        FOREIGN KEY (blocker_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_block_blocked
        FOREIGN KEY (blocked_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_block_not_self
        CHECK (blocker_id <> blocked_id),
    CONSTRAINT ck_user_block_release
        CHECK (released_at IS NULL OR released_at >= created_at)
);

CREATE TABLE report (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id             BIGINT NOT NULL,
    target_user_id          BIGINT,
    direction_post_id       BIGINT,
    answer_id               BIGINT,
    reason_code             VARCHAR(50) NOT NULL,
    detail                  TEXT,
    status                  VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    resolved_at             TIMESTAMPTZ,

    CONSTRAINT fk_report_reporter
        FOREIGN KEY (reporter_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_target_user
        FOREIGN KEY (target_user_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_direction_post
        FOREIGN KEY (direction_post_id) REFERENCES direction_post (id) ON DELETE RESTRICT,
    CONSTRAINT fk_report_answer
        FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE RESTRICT,
    CONSTRAINT ck_report_exactly_one_target
        CHECK (num_nonnulls(target_user_id, direction_post_id, answer_id) = 1),
    CONSTRAINT ck_report_reason
        CHECK (btrim(reason_code) <> ''),
    CONSTRAINT ck_report_status
        CHECK (status IN (
            'RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW', 'ACTIONED',
            'NO_VIOLATION', 'MORE_INFO_REQUIRED'
        )),
    CONSTRAINT ck_report_resolution
        CHECK (resolved_at IS NULL OR resolved_at >= created_at)
);

CREATE TABLE moderation_review (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id               BIGINT NOT NULL,
    reviewer_id             BIGINT NOT NULL,
    decision                VARCHAR(30) NOT NULL,
    action_type             VARCHAR(50) NOT NULL,
    internal_note           TEXT,
    reviewed_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_moderation_review_report
        FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE RESTRICT,
    CONSTRAINT fk_moderation_review_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT ck_moderation_review_decision
        CHECK (decision IN ('ACTIONED', 'NO_VIOLATION', 'MORE_INFO_REQUIRED')),
    CONSTRAINT ck_moderation_review_action_type
        CHECK (btrim(action_type) <> '')
);

-- -----------------------------------------------------------------------------
-- 5. 알림과 트랜잭셔널 Outbox
-- -----------------------------------------------------------------------------

CREATE TABLE push_device (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    platform                VARCHAR(20) NOT NULL,
    token_ciphertext        BYTEA NOT NULL,
    token_fingerprint       VARCHAR(128) NOT NULL,
    device_status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_seen_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    revoked_at              TIMESTAMPTZ,

    CONSTRAINT fk_push_device_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_push_device_platform
        CHECK (platform IN ('IOS', 'ANDROID')),
    CONSTRAINT ck_push_device_status
        CHECK (device_status IN ('ACTIVE', 'INVALID', 'REVOKED')),
    CONSTRAINT ck_push_device_revoked_at
        CHECK ((device_status = 'REVOKED') = (revoked_at IS NOT NULL))
);

CREATE TABLE notification_preference (
    notification_type       VARCHAR(50) NOT NULL,
    user_id                 BIGINT NOT NULL,
    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    quiet_start             TIME,
    quiet_end               TIME,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT pk_notification_preference
        PRIMARY KEY (notification_type, user_id),
    CONSTRAINT fk_notification_preference_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_preference_type
        CHECK (notification_type IN (
            'ANSWER_RECEIVED', 'DIRECTION_POST_RECEIVED', 'REPORT_RESOLVED',
            'QUESTION_PROPOSAL_REVIEWED', 'DAILY_QUESTION_ASSIGNED'
        )),
    CONSTRAINT ck_notification_preference_quiet_hours
        CHECK (num_nonnulls(quiet_start, quiet_end) IN (0, 2))
);

CREATE TABLE outbox_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type          VARCHAR(100) NOT NULL,
    aggregate_id            BIGINT NOT NULL,
    event_type              VARCHAR(100) NOT NULL,
    dedup_key               VARCHAR(255) NOT NULL,
    payload                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count           INTEGER NOT NULL DEFAULT 0,
    next_attempt_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    processed_at            TIMESTAMPTZ,

    CONSTRAINT uq_outbox_event_dedup
        UNIQUE (dedup_key),
    CONSTRAINT ck_outbox_event_aggregate_type
        CHECK (aggregate_type IN (
            'DIRECTION_POST', 'POST_RECIPIENT', 'ANSWER', 'QUESTION_ASSIGNMENT',
            'QUESTION_PROPOSAL', 'REPORT'
        )),
    CONSTRAINT ck_outbox_event_event_type
        CHECK (event_type IN (
            'RECIPIENT_MATCH_REQUESTED', 'RECIPIENTS_CONFIRMED', 'DIRECTION_POST_EXPIRED',
            'ANSWER_PUBLISHED', 'DAILY_QUESTION_ASSIGNED', 'QUESTION_PROPOSAL_REVIEWED',
            'REPORT_RESOLVED'
        )),
    CONSTRAINT ck_outbox_event_payload
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_event_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'DEAD')),
    CONSTRAINT ck_outbox_event_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_event_processed_at
        CHECK (
            (status = 'PROCESSED') = (processed_at IS NOT NULL)
            AND (processed_at IS NULL OR processed_at >= created_at)
        )
);

CREATE TABLE notification (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id            BIGINT NOT NULL,
    outbox_event_id         BIGINT NOT NULL,
    notification_type       VARCHAR(50) NOT NULL,
    dedup_key               VARCHAR(255) NOT NULL,
    direction_post_id       BIGINT,
    answer_id               BIGINT,
    status                  VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    read_at                 TIMESTAMPTZ,

    CONSTRAINT fk_notification_recipient
        FOREIGN KEY (recipient_id) REFERENCES user_account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_outbox
        FOREIGN KEY (outbox_event_id) REFERENCES outbox_event (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_post
        FOREIGN KEY (direction_post_id) REFERENCES direction_post (id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_answer
        FOREIGN KEY (answer_id) REFERENCES answer (id) ON DELETE SET NULL,
    CONSTRAINT uq_notification_recipient_dedup
        UNIQUE (recipient_id, dedup_key),
    CONSTRAINT ck_notification_type
        CHECK (notification_type IN (
            'ANSWER_RECEIVED', 'DIRECTION_POST_RECEIVED', 'REPORT_RESOLVED',
            'QUESTION_PROPOSAL_REVIEWED', 'DAILY_QUESTION_ASSIGNED'
        )),
    CONSTRAINT ck_notification_target
        CHECK (num_nonnulls(direction_post_id, answer_id) <= 1),
    CONSTRAINT ck_notification_status
        CHECK (status IN ('UNREAD', 'READ', 'DISMISSED', 'REVOKED')),
    CONSTRAINT ck_notification_read_at
        CHECK (
            read_at IS NULL
            OR (read_at >= created_at AND status IN ('READ', 'DISMISSED'))
        )
);

CREATE TABLE notification_delivery (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id         BIGINT NOT NULL,
    push_device_id          BIGINT NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count           INTEGER NOT NULL DEFAULT 0,
    next_attempt_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    sent_at                 TIMESTAMPTZ,
    provider_message_id     VARCHAR(255),

    CONSTRAINT fk_notification_delivery_notification
        FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_delivery_device
        FOREIGN KEY (push_device_id) REFERENCES push_device (id) ON DELETE RESTRICT,
    CONSTRAINT uq_notification_delivery_device
        UNIQUE (notification_id, push_device_id),
    CONSTRAINT ck_notification_delivery_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED', 'DEAD')),
    CONSTRAINT ck_notification_delivery_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_notification_delivery_sent_at
        CHECK (
            (status = 'SENT') = (sent_at IS NOT NULL)
            AND (sent_at IS NULL OR sent_at >= created_at)
        )
);

-- -----------------------------------------------------------------------------
-- 6. 테이블 간 불변식
-- -----------------------------------------------------------------------------

CREATE FUNCTION enforce_question_text_immutability()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_TABLE_NAME = 'approved_question'
       AND NEW.question_text IS DISTINCT FROM OLD.question_text THEN
        RAISE EXCEPTION 'approved_question.question_text is immutable'
            USING ERRCODE = '23514';
    END IF;

    IF TG_TABLE_NAME = 'question_proposal'
       AND OLD.status <> 'DRAFT'
       AND NEW.proposed_text IS DISTINCT FROM OLD.proposed_text THEN
        RAISE EXCEPTION 'submitted question_proposal.proposed_text is immutable'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_approved_question_text_immutable
BEFORE UPDATE OF question_text ON approved_question
FOR EACH ROW EXECUTE FUNCTION enforce_question_text_immutability();

CREATE TRIGGER tr_question_proposal_text_immutable_after_submit
BEFORE UPDATE OF proposed_text ON question_proposal
FOR EACH ROW EXECUTE FUNCTION enforce_question_text_immutability();

CREATE FUNCTION enforce_direction_post_question_active()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_status VARCHAR(30);
BEGIN
    SELECT status INTO current_status
    FROM approved_question
    WHERE id = NEW.approved_question_id;

    IF current_status <> 'ACTIVE' THEN
        RAISE EXCEPTION 'approved_question % must be ACTIVE (current: %)',
            NEW.approved_question_id, current_status
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_direction_post_question_active
AFTER INSERT OR UPDATE OF approved_question_id ON direction_post
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_direction_post_question_active();

CREATE FUNCTION enforce_post_recipient_not_sender()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM direction_post
        WHERE id = NEW.post_id
          AND sender_id = NEW.recipient_id
    ) THEN
        RAISE EXCEPTION 'direction_post sender cannot receive own post'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_post_recipient_not_sender
AFTER INSERT OR UPDATE OF post_id, recipient_id ON post_recipient
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_post_recipient_not_sender();

-- 활성 미처리 수신 용량은 recipient_receive_state.active_unhandled_count로 집계하지만,
-- 그 값의 근거는 capacity_released_at IS NULL인 post_recipient 행 수다. 상태와 해제 시각이
-- 어긋나면 카운터를 재계산할 수 없으므로 둘의 동치를 커밋 시점에 검사한다.
-- T6·T6A·T6B가 상태 전이와 조건부 해제를 서로 다른 문장으로 수행하므로 지연 트리거다.
--
-- NEW를 쓰지 않고 행을 다시 읽는 이유: 지연 AFTER ROW 트리거는 실행 시점만 커밋으로
-- 미룰 뿐, 전달받는 튜플은 자신을 큐에 넣은 문장 당시의 버전이다. NEW로 판정하면
-- "상태 전이 문장" 시점의 중간 상태(해제 전)를 보고 실패한다. 같은 트랜잭션의 최종
-- 상태를 검사해야 하므로 assert_post_has_content와 같은 방식으로 현재 행을 조회한다.
CREATE FUNCTION enforce_post_recipient_capacity_release()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_row RECORD;
BEGIN
    SELECT status, capacity_released_at
    INTO current_row
    FROM post_recipient
    WHERE id = NEW.id;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    IF (current_row.status IN ('ANSWERED', 'SKIPPED', 'EXPIRED', 'BLOCKED'))
       <> (current_row.capacity_released_at IS NOT NULL) THEN
        RAISE EXCEPTION
            'post_recipient % status % and capacity_released_at % disagree',
            NEW.id, current_row.status, current_row.capacity_released_at
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_post_recipient_capacity_release
AFTER INSERT OR UPDATE OF status, capacity_released_at ON post_recipient
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_post_recipient_capacity_release();

CREATE FUNCTION assert_post_has_content(target_post_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM direction_post p
        WHERE p.id = target_post_id
          AND p.status = 'ACTIVE'
          AND NULLIF(btrim(p.body_text), '') IS NULL
          AND NOT EXISTS (
              SELECT 1
              FROM media_attachment ma
              JOIN media_asset m ON m.id = ma.media_id
              WHERE ma.post_id = p.id
                AND m.status = 'READY'
          )
    ) THEN
        RAISE EXCEPTION 'active direction_post % requires body_text or READY media', target_post_id
            USING ERRCODE = '23514';
    END IF;
END;
$$;

CREATE FUNCTION assert_answer_has_content(target_answer_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM answer a
        WHERE a.id = target_answer_id
          AND a.status = 'PUBLISHED'
          AND NULLIF(btrim(a.body_text), '') IS NULL
          AND NOT EXISTS (
              SELECT 1
              FROM media_attachment ma
              JOIN media_asset m ON m.id = ma.media_id
              WHERE ma.answer_id = a.id
                AND m.status = 'READY'
          )
    ) THEN
        RAISE EXCEPTION 'published answer % requires body_text or READY media', target_answer_id
            USING ERRCODE = '23514';
    END IF;
END;
$$;

CREATE FUNCTION enforce_post_has_content()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM assert_post_has_content(OLD.id);
        RETURN OLD;
    END IF;

    PERFORM assert_post_has_content(NEW.id);
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_direction_post_has_content
AFTER INSERT OR UPDATE ON direction_post
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_post_has_content();

CREATE FUNCTION enforce_answer_has_content()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM assert_answer_has_content(OLD.id);
        RETURN OLD;
    END IF;

    PERFORM assert_answer_has_content(NEW.id);
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_answer_has_content
AFTER INSERT OR UPDATE ON answer
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_answer_has_content();

-- 첨부를 붙이거나 떼어낸 뒤에도 콘텐츠 조건이 유지되는지 재검사한다.
-- UPDATE로 첨부 대상이 옮겨간 경우 원래 대상도 다시 확인한다.
CREATE FUNCTION enforce_media_attachment_preserves_content()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN
        IF OLD.post_id IS NOT NULL THEN
            PERFORM assert_post_has_content(OLD.post_id);
        END IF;
        IF OLD.answer_id IS NOT NULL THEN
            PERFORM assert_answer_has_content(OLD.answer_id);
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF NEW.post_id IS NOT NULL THEN
        PERFORM assert_post_has_content(NEW.post_id);
    END IF;
    IF NEW.answer_id IS NOT NULL THEN
        PERFORM assert_answer_has_content(NEW.answer_id);
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_media_attachment_preserves_content
AFTER INSERT OR UPDATE OR DELETE ON media_attachment
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_media_attachment_preserves_content();

-- media_id가 media_attachment의 PK이므로 이 미디어의 첨부는 최대 한 건이다.
CREATE FUNCTION enforce_media_status_preserves_content()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    attachment RECORD;
BEGIN
    SELECT post_id, answer_id INTO attachment
    FROM media_attachment
    WHERE media_id = NEW.id;

    IF FOUND THEN
        IF attachment.post_id IS NOT NULL THEN
            PERFORM assert_post_has_content(attachment.post_id);
        END IF;
        IF attachment.answer_id IS NOT NULL THEN
            PERFORM assert_answer_has_content(attachment.answer_id);
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER ct_media_status_preserves_content
AFTER UPDATE OF status ON media_asset
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_media_status_preserves_content();

-- -----------------------------------------------------------------------------
-- 7. 조회·작업자 인덱스
-- -----------------------------------------------------------------------------

CREATE INDEX region_code_parent_idx
    ON region_code (parent_code) WHERE parent_code IS NOT NULL;

-- 매칭 쿼리는 항상 receive_allowed = TRUE 후보만 본다. 부분 인덱스로 두면
-- 수신을 끈 사용자의 좌표가 인덱스에 들어가지 않아 크기와 갱신 비용이 줄어든다.
CREATE INDEX active_user_presence_position_gix
    ON active_user_presence USING GIST (position) WHERE receive_allowed = TRUE;

CREATE INDEX active_user_presence_expiry_idx
    ON active_user_presence (expires_at) WHERE receive_allowed = TRUE;

CREATE INDEX approved_question_active_idx
    ON approved_question (active_from, active_until) WHERE status = 'ACTIVE';

-- 같은 code의 두 버전이 동시에 ACTIVE가 되면 애플리케이션이 현재 방향 정책을
-- 모호하지 않게 고를 수 없다. INACTIVE·ARCHIVED 버전은 code가 겹쳐도 된다.
CREATE UNIQUE INDEX uq_direction_scheme_active
    ON direction_scheme (code) WHERE status = 'ACTIVE';

-- -----------------------------------------------------------------------------
-- FK 컬럼 인덱스
-- PostgreSQL은 FK에 인덱스를 자동 생성하지 않는다. 아래는 기존 PK·UNIQUE·부분
-- 인덱스의 선두 컬럼으로 커버되지 않아 RESTRICT·CASCADE·SET NULL 검사와 역방향
-- 조회가 순차 스캔이 되는 FK만 모은 것이다.
-- -----------------------------------------------------------------------------

CREATE INDEX user_account_region_idx
    ON user_account (coarse_region_code);

CREATE INDEX active_user_presence_region_idx
    ON active_user_presence (coarse_region_code);

CREATE INDEX question_proposal_proposer_idx
    ON question_proposal (proposer_id);

CREATE INDEX question_proposal_review_reviewer_idx
    ON question_proposal_review (reviewer_id);

CREATE INDEX approved_question_approver_idx
    ON approved_question (approved_by) WHERE approved_by IS NOT NULL;

CREATE INDEX media_asset_owner_idx
    ON media_asset (owner_id);

CREATE INDEX direction_post_question_idx
    ON direction_post (approved_question_id);

CREATE INDEX direction_post_region_idx
    ON direction_post (coarse_region_code);

CREATE INDEX post_audience_segment_idx
    ON post_audience (direction_scheme_id, selected_segment_key);

CREATE INDEX post_recipient_region_idx
    ON post_recipient (matched_region_code);

CREATE INDEX answer_region_idx
    ON answer (coarse_region_code);

CREATE INDEX report_target_user_idx
    ON report (target_user_id) WHERE target_user_id IS NOT NULL;

CREATE INDEX report_direction_post_idx
    ON report (direction_post_id) WHERE direction_post_id IS NOT NULL;

CREATE INDEX report_answer_idx
    ON report (answer_id) WHERE answer_id IS NOT NULL;

CREATE INDEX report_queue_idx
    ON report (status, created_at)
    WHERE status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW');

CREATE INDEX moderation_review_report_idx
    ON moderation_review (report_id, reviewed_at DESC);

CREATE INDEX moderation_review_reviewer_idx
    ON moderation_review (reviewer_id);

CREATE INDEX push_device_user_idx
    ON push_device (user_id) WHERE device_status = 'ACTIVE';

CREATE INDEX notification_preference_user_idx
    ON notification_preference (user_id);

CREATE INDEX notification_outbox_idx
    ON notification (outbox_event_id);

CREATE INDEX notification_post_idx
    ON notification (direction_post_id) WHERE direction_post_id IS NOT NULL;

CREATE INDEX notification_answer_idx
    ON notification (answer_id) WHERE answer_id IS NOT NULL;

CREATE INDEX notification_delivery_device_idx
    ON notification_delivery (push_device_id);

CREATE INDEX question_proposal_review_queue_idx
    ON question_proposal (status, updated_at)
    WHERE status IN ('SUBMITTED', 'UNDER_REVIEW');

CREATE INDEX question_proposal_review_history_idx
    ON question_proposal_review (proposal_id, reviewed_at DESC);

CREATE INDEX question_assignment_history_idx
    ON question_assignment (approved_question_id, assigned_at DESC);

CREATE INDEX direction_post_sender_idx
    ON direction_post (sender_id, submitted_at DESC);

CREATE INDEX direction_post_expiry_idx
    ON direction_post (expires_at, id) WHERE status IN ('MATCHING', 'ACTIVE');

CREATE INDEX post_recipient_inbox_idx
    ON post_recipient (recipient_id, status, matched_at DESC);

CREATE INDEX post_recipient_capacity_idx
    ON post_recipient (recipient_id, matched_at DESC)
    WHERE capacity_released_at IS NULL;

CREATE INDEX recipient_receive_selection_idx
    ON recipient_receive_state (
        active_unhandled_count, recent_received_count, last_received_at
    );

CREATE INDEX answer_recipient_idx
    ON answer (post_recipient_id, published_at DESC);

CREATE INDEX user_block_reverse_idx
    ON user_block (blocked_id, blocker_id) WHERE released_at IS NULL;

CREATE UNIQUE INDEX uq_open_report_user
    ON report (reporter_id, target_user_id)
    WHERE target_user_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW');

CREATE UNIQUE INDEX uq_open_report_post
    ON report (reporter_id, direction_post_id)
    WHERE direction_post_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW');

CREATE UNIQUE INDEX uq_open_report_answer
    ON report (reporter_id, answer_id)
    WHERE answer_id IS NOT NULL
      AND status IN ('RECEIVED', 'AUTO_HIDDEN', 'UNDER_REVIEW');

CREATE UNIQUE INDEX uq_active_push_token
    ON push_device (token_fingerprint) WHERE device_status = 'ACTIVE';

CREATE INDEX outbox_event_dispatch_idx
    ON outbox_event (status, next_attempt_at, id)
    WHERE status IN ('PENDING', 'FAILED');

CREATE INDEX notification_inbox_idx
    ON notification (recipient_id, read_at, created_at DESC);

CREATE INDEX notification_delivery_dispatch_idx
    ON notification_delivery (status, next_attempt_at, id)
    WHERE status IN ('PENDING', 'FAILED');

-- -----------------------------------------------------------------------------
-- 8. 확정된 MVP 방향 정책: 8개 45도 구간
-- -----------------------------------------------------------------------------

WITH inserted_scheme AS (
    INSERT INTO direction_scheme (
        code, version, type, segment_count, start_offset_deg, status
    )
    VALUES ('OCTANT', 1, 'EQUAL_SEGMENTS', 8, 337.500, 'ACTIVE')
    RETURNING id
)
INSERT INTO direction_segment (
    scheme_id, segment_key, display_name,
    center_bearing_deg, angular_width_deg, sort_order
)
SELECT id, segment_key, display_name, center_bearing_deg, 45.000, sort_order
FROM inserted_scheme
CROSS JOIN (VALUES
    ('N',  '북',   0.000, 0),
    ('NE', '북동', 45.000, 1),
    ('E',  '동',   90.000, 2),
    ('SE', '남동', 135.000, 3),
    ('S',  '남',   180.000, 4),
    ('SW', '남서', 225.000, 5),
    ('W',  '서',   270.000, 6),
    ('NW', '북서', 315.000, 7)
) AS segment(segment_key, display_name, center_bearing_deg, sort_order);

COMMIT;
