-- #113: 운영자가 필터링 authority를 바꾼 행위의 단일 감사 원장.
--
-- 기존 이력 테이블(release_promotion_history, filter_job_status_history,
-- manual_review_priority_evaluation)을 대체하지 않는다. 그것들은 각 도메인
-- 이벤트의 원장이고, 이 테이블은 "사람이 무엇을 왜 바꿨는가"만 담는다.
-- 기존 원장을 옮기면 이미 배포된 계약을 깨고 마이그레이션 위험만 커진다.
--
-- append-only다. 애플리케이션에 UPDATE·DELETE 경로를 두지 않는다 — 감사
-- 이력을 고칠 수 있으면 감사가 아니다.
CREATE TABLE operator_action_audit (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_user_id    BIGINT NOT NULL,
    action_type         VARCHAR(50) NOT NULL,
    target_type         VARCHAR(30) NOT NULL,
    target_key          VARCHAR(200) NOT NULL,
    reason_code         VARCHAR(30) NOT NULL,
    reason_text         VARCHAR(500) NOT NULL,
    policy_version      VARCHAR(50) NOT NULL,
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT ck_operator_action_audit_operator
        CHECK (operator_user_id > 0),
    CONSTRAINT ck_operator_action_audit_target_key
        CHECK (btrim(target_key) <> ''),
    -- 형식만 채운 근거를 막는다. 공백뿐인 reason은 "왜"가 없는 것과 같다.
    CONSTRAINT ck_operator_action_audit_reason_code
        CHECK (btrim(reason_code) <> ''),
    CONSTRAINT ck_operator_action_audit_reason_text
        CHECK (btrim(reason_text) <> ''),
    CONSTRAINT ck_operator_action_audit_policy_version
        CHECK (btrim(policy_version) <> ''),
    -- 애플리케이션 검증을 우회해 들어온 값이 있으면 읽을 때 valueOf가 실패해
    -- 감사 조회 자체가 막힌다. 쓰기 시점에 거절해 그 상황을 만들지 않는다.
    CONSTRAINT ck_operator_action_audit_action_type
        CHECK (action_type IN (
            'RELEASE_MARK_OFFLINE_EVALUATED', 'RELEASE_DESIGNATE_SHADOW', 'RELEASE_DESIGNATE_CANARY',
            'RELEASE_PROMOTE', 'RELEASE_ROLLBACK', 'RELEASE_DEMOTED_BY_PROMOTION',
            'MANUAL_REVIEW_DECIDE', 'APPEAL_DECIDE', 'APPEAL_EXTEND_EXPIRY',
            'SNAPSHOT_HEALTH_CONFIRM_PERMANENT', 'SNAPSHOT_EMERGENCY_MIGRATION'
        )),
    CONSTRAINT ck_operator_action_audit_target_type
        CHECK (target_type IN ('FILTER_RELEASE', 'MANUAL_REVIEW_CASE', 'APPEAL_CASE', 'SNAPSHOT_HEALTH'))
);

-- 대상 하나의 변경 이력을 시간순으로 훑는 조회.
CREATE INDEX operator_action_audit_target_idx
    ON operator_action_audit (target_type, target_key, occurred_at);

-- "이 운영자가 무엇을 했는가" 조회.
CREATE INDEX operator_action_audit_operator_idx
    ON operator_action_audit (operator_user_id, occurred_at);

COMMENT ON TABLE operator_action_audit IS
    '운영자의 필터링 authority 변경에 대한 append-only 감사 원장. actor·reason·policy version·시간을 함께 남긴다(INV-APL-012).';
COMMENT ON COLUMN operator_action_audit.target_key IS
    '대상 식별자의 문자열 표현. snapshot health는 modelSnapshot 문자열이, 나머지는 숫자 id가 키라서 한 컬럼으로 통일했다. FK로 참조하지 않는다 — 대상 행이 지워져도 감사 이력은 남아야 한다.';
COMMENT ON COLUMN operator_action_audit.policy_version IS
    '행위 시점의 정책 식별자. 행위마다 관련 정책이 달라 전역 단일 버전을 두지 않고 호출 지점이 자신의 정책 버전을 넘긴다.';
COMMENT ON COLUMN operator_action_audit.reason_text IS
    '운영자가 직접 입력한 근거. 서버가 기본값을 채우지 않는다 — 채우면 감사 이력에 "왜"가 없는 것과 같다.';
