CREATE TABLE push_dispatch_group (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id          BIGINT NOT NULL,
    notification_type     VARCHAR(50) NOT NULL,
    aggregation_key       VARCHAR(255) NOT NULL,
    status                VARCHAR(20) NOT NULL,
    window_started_at     TIMESTAMPTZ NOT NULL,
    collect_until         TIMESTAMPTZ NOT NULL,
    policy_expires_at     TIMESTAMPTZ NOT NULL,
    attempt_count         INTEGER NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ NOT NULL,
    budget_local_date     DATE,
    budget_consumed_at    TIMESTAMPTZ,
    first_attempted_at    TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    completed_at          TIMESTAMPTZ,

    CONSTRAINT fk_push_dispatch_group_recipient
        FOREIGN KEY (recipient_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT uq_push_dispatch_group_aggregation_key UNIQUE (aggregation_key),
    CONSTRAINT ck_push_dispatch_group_type CHECK (notification_type IN (
        'ANSWER_RECEIVED', 'ANSWER_REACTED', 'DIRECTION_POST_RECEIVED',
        'REPORT_RESOLVED', 'QUESTION_PROPOSAL_REVIEWED', 'QUESTION_RECOMMENDED')),
    CONSTRAINT ck_push_dispatch_group_status CHECK (status IN (
        'COLLECTING', 'PENDING', 'PROCESSING', 'FAILED', 'COMPLETED', 'CANCELLED', 'DEAD')),
    CONSTRAINT ck_push_dispatch_group_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_push_dispatch_group_window
        CHECK (collect_until >= window_started_at AND policy_expires_at >= collect_until),
    CONSTRAINT ck_push_dispatch_group_budget
        CHECK ((budget_local_date IS NULL) = (budget_consumed_at IS NULL)),
    CONSTRAINT ck_push_dispatch_group_first_attempt
        CHECK (first_attempted_at IS NULL OR budget_consumed_at IS NOT NULL),
    CONSTRAINT ck_push_dispatch_group_completed_at CHECK (
        (status IN ('COMPLETED', 'CANCELLED', 'DEAD')) = (completed_at IS NOT NULL))
);

CREATE TABLE push_dispatch_group_member (
    group_id        BIGINT NOT NULL,
    notification_id BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_push_dispatch_group_member PRIMARY KEY (group_id, notification_id),
    CONSTRAINT fk_push_dispatch_group_member_group
        FOREIGN KEY (group_id) REFERENCES push_dispatch_group (id) ON DELETE CASCADE,
    CONSTRAINT fk_push_dispatch_group_member_notification
        FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_push_dispatch_group_member_notification
    ON push_dispatch_group_member (notification_id);

CREATE TABLE push_daily_budget (
    user_id           BIGINT NOT NULL,
    budget_date       DATE NOT NULL,
    consumed_total    INTEGER NOT NULL DEFAULT 0,
    consumed_general  INTEGER NOT NULL DEFAULT 0,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pk_push_daily_budget PRIMARY KEY (user_id, budget_date),
    CONSTRAINT fk_push_daily_budget_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_push_daily_budget_counts CHECK (
        consumed_total >= 0 AND consumed_general >= 0
        AND consumed_general <= consumed_total)
);

CREATE UNIQUE INDEX uq_push_dispatch_group_collecting
    ON push_dispatch_group (recipient_id, notification_type)
    WHERE status = 'COLLECTING';

CREATE INDEX push_dispatch_group_due_idx
    ON push_dispatch_group (status, next_attempt_at, id)
    WHERE status IN ('COLLECTING', 'PENDING', 'FAILED', 'PROCESSING');

CREATE INDEX push_dispatch_group_recommendation_history_idx
    ON push_dispatch_group (recipient_id, first_attempted_at DESC)
    WHERE notification_type = 'QUESTION_RECOMMENDED' AND first_attempted_at IS NOT NULL;
