-- 국가 선택·검증의 기준 데이터로 ISO 3166-1 alpha-2 국가를 region_code의 COUNTRY 행으로 적재한다.
-- user_account.country_code(fk_user_account_country)와 existsCountry 검증이 이 행을 참조한다.
-- 이미 같은 code가 있으면 건드리지 않아 재적용과 기존 데이터에 안전하다.
-- REGION 이하 하위 지역은 이 마이그레이션의 범위가 아니다.
INSERT INTO region_code (code, parent_code, display_name, level)
VALUES
    ('AD', NULL, '안도라', 'COUNTRY'),
    ('AE', NULL, '아랍에미리트', 'COUNTRY'),
    ('AF', NULL, '아프가니스탄', 'COUNTRY'),
    ('AG', NULL, '앤티가 바부다', 'COUNTRY'),
    ('AI', NULL, '앵귈라', 'COUNTRY'),
    ('AL', NULL, '알바니아', 'COUNTRY'),
    ('AM', NULL, '아르메니아', 'COUNTRY'),
    ('AO', NULL, '앙골라', 'COUNTRY'),
    ('AQ', NULL, '남극', 'COUNTRY'),
    ('AR', NULL, '아르헨티나', 'COUNTRY'),
    ('AS', NULL, '아메리칸사모아', 'COUNTRY'),
    ('AT', NULL, '오스트리아', 'COUNTRY'),
    ('AU', NULL, '오스트레일리아', 'COUNTRY'),
    ('AW', NULL, '아루바', 'COUNTRY'),
    ('AX', NULL, '올란드 제도', 'COUNTRY'),
    ('AZ', NULL, '아제르바이잔', 'COUNTRY'),
    ('BA', NULL, '보스니아 헤르체고비나', 'COUNTRY'),
    ('BB', NULL, '바베이도스', 'COUNTRY'),
    ('BD', NULL, '방글라데시', 'COUNTRY'),
    ('BE', NULL, '벨기에', 'COUNTRY'),
    ('BF', NULL, '부르키나파소', 'COUNTRY'),
    ('BG', NULL, '불가리아', 'COUNTRY'),
    ('BH', NULL, '바레인', 'COUNTRY'),
    ('BI', NULL, '부룬디', 'COUNTRY'),
    ('BJ', NULL, '베냉', 'COUNTRY'),
    ('BL', NULL, '생바르텔레미', 'COUNTRY'),
    ('BM', NULL, '버뮤다', 'COUNTRY'),
    ('BN', NULL, '브루나이', 'COUNTRY'),
    ('BO', NULL, '볼리비아', 'COUNTRY'),
    ('BQ', NULL, '보네르, 신트외스타티우스, 사바', 'COUNTRY'),
    ('BR', NULL, '브라질', 'COUNTRY'),
    ('BS', NULL, '바하마', 'COUNTRY'),
    ('BT', NULL, '부탄', 'COUNTRY'),
    ('BV', NULL, '부베 섬', 'COUNTRY'),
    ('BW', NULL, '보츠와나', 'COUNTRY'),
    ('BY', NULL, '벨라루스', 'COUNTRY'),
    ('BZ', NULL, '벨리즈', 'COUNTRY'),
    ('CA', NULL, '캐나다', 'COUNTRY'),
    ('CC', NULL, '코코스 제도', 'COUNTRY'),
    ('CD', NULL, '콩고민주공화국', 'COUNTRY'),
    ('CF', NULL, '중앙아프리카공화국', 'COUNTRY'),
    ('CG', NULL, '콩고공화국', 'COUNTRY'),
    ('CH', NULL, '스위스', 'COUNTRY'),
    ('CI', NULL, '코트디부아르', 'COUNTRY'),
    ('CK', NULL, '쿡 제도', 'COUNTRY'),
    ('CL', NULL, '칠레', 'COUNTRY'),
    ('CM', NULL, '카메룬', 'COUNTRY'),
    ('CN', NULL, '중국', 'COUNTRY'),
    ('CO', NULL, '콜롬비아', 'COUNTRY'),
    ('CR', NULL, '코스타리카', 'COUNTRY'),
    ('CU', NULL, '쿠바', 'COUNTRY'),
    ('CV', NULL, '카보베르데', 'COUNTRY'),
    ('CW', NULL, '퀴라소', 'COUNTRY'),
    ('CX', NULL, '크리스마스 섬', 'COUNTRY'),
    ('CY', NULL, '키프로스', 'COUNTRY'),
    ('CZ', NULL, '체코', 'COUNTRY'),
    ('DE', NULL, '독일', 'COUNTRY'),
    ('DJ', NULL, '지부티', 'COUNTRY'),
    ('DK', NULL, '덴마크', 'COUNTRY'),
    ('DM', NULL, '도미니카', 'COUNTRY'),
    ('DO', NULL, '도미니카공화국', 'COUNTRY'),
    ('DZ', NULL, '알제리', 'COUNTRY'),
    ('EC', NULL, '에콰도르', 'COUNTRY'),
    ('EE', NULL, '에스토니아', 'COUNTRY'),
    ('EG', NULL, '이집트', 'COUNTRY'),
    ('EH', NULL, '서사하라', 'COUNTRY'),
    ('ER', NULL, '에리트레아', 'COUNTRY'),
    ('ES', NULL, '스페인', 'COUNTRY'),
    ('ET', NULL, '에티오피아', 'COUNTRY'),
    ('FI', NULL, '핀란드', 'COUNTRY'),
    ('FJ', NULL, '피지', 'COUNTRY'),
    ('FK', NULL, '포클랜드 제도', 'COUNTRY'),
    ('FM', NULL, '미크로네시아', 'COUNTRY'),
    ('FO', NULL, '페로 제도', 'COUNTRY'),
    ('FR', NULL, '프랑스', 'COUNTRY'),
    ('GA', NULL, '가봉', 'COUNTRY'),
    ('GB', NULL, '영국', 'COUNTRY'),
    ('GD', NULL, '그레나다', 'COUNTRY'),
    ('GE', NULL, '조지아', 'COUNTRY'),
    ('GF', NULL, '프랑스령 기아나', 'COUNTRY'),
    ('GG', NULL, '건지 섬', 'COUNTRY'),
    ('GH', NULL, '가나', 'COUNTRY'),
    ('GI', NULL, '지브롤터', 'COUNTRY'),
    ('GL', NULL, '그린란드', 'COUNTRY'),
    ('GM', NULL, '감비아', 'COUNTRY'),
    ('GN', NULL, '기니', 'COUNTRY'),
    ('GP', NULL, '과들루프', 'COUNTRY'),
    ('GQ', NULL, '적도 기니', 'COUNTRY'),
    ('GR', NULL, '그리스', 'COUNTRY'),
    ('GS', NULL, '사우스조지아 사우스샌드위치 제도', 'COUNTRY'),
    ('GT', NULL, '과테말라', 'COUNTRY'),
    ('GU', NULL, '괌', 'COUNTRY'),
    ('GW', NULL, '기니비사우', 'COUNTRY'),
    ('GY', NULL, '가이아나', 'COUNTRY'),
    ('HK', NULL, '홍콩', 'COUNTRY'),
    ('HM', NULL, '허드 맥도널드 제도', 'COUNTRY'),
    ('HN', NULL, '온두라스', 'COUNTRY'),
    ('HR', NULL, '크로아티아', 'COUNTRY'),
    ('HT', NULL, '아이티', 'COUNTRY'),
    ('HU', NULL, '헝가리', 'COUNTRY'),
    ('ID', NULL, '인도네시아', 'COUNTRY'),
    ('IE', NULL, '아일랜드', 'COUNTRY'),
    ('IL', NULL, '이스라엘', 'COUNTRY'),
    ('IM', NULL, '맨 섬', 'COUNTRY'),
    ('IN', NULL, '인도', 'COUNTRY'),
    ('IO', NULL, '영국령 인도양 지역', 'COUNTRY'),
    ('IQ', NULL, '이라크', 'COUNTRY'),
    ('IR', NULL, '이란', 'COUNTRY'),
    ('IS', NULL, '아이슬란드', 'COUNTRY'),
    ('IT', NULL, '이탈리아', 'COUNTRY'),
    ('JE', NULL, '저지 섬', 'COUNTRY'),
    ('JM', NULL, '자메이카', 'COUNTRY'),
    ('JO', NULL, '요르단', 'COUNTRY'),
    ('JP', NULL, '일본', 'COUNTRY'),
    ('KE', NULL, '케냐', 'COUNTRY'),
    ('KG', NULL, '키르기스스탄', 'COUNTRY'),
    ('KH', NULL, '캄보디아', 'COUNTRY'),
    ('KI', NULL, '키리바시', 'COUNTRY'),
    ('KM', NULL, '코모로', 'COUNTRY'),
    ('KN', NULL, '세인트키츠 네비스', 'COUNTRY'),
    ('KP', NULL, '북한', 'COUNTRY'),
    ('KR', NULL, '대한민국', 'COUNTRY'),
    ('KW', NULL, '쿠웨이트', 'COUNTRY'),
    ('KY', NULL, '케이맨 제도', 'COUNTRY'),
    ('KZ', NULL, '카자흐스탄', 'COUNTRY'),
    ('LA', NULL, '라오스', 'COUNTRY'),
    ('LB', NULL, '레바논', 'COUNTRY'),
    ('LC', NULL, '세인트루시아', 'COUNTRY'),
    ('LI', NULL, '리히텐슈타인', 'COUNTRY'),
    ('LK', NULL, '스리랑카', 'COUNTRY'),
    ('LR', NULL, '라이베리아', 'COUNTRY'),
    ('LS', NULL, '레소토', 'COUNTRY'),
    ('LT', NULL, '리투아니아', 'COUNTRY'),
    ('LU', NULL, '룩셈부르크', 'COUNTRY'),
    ('LV', NULL, '라트비아', 'COUNTRY'),
    ('LY', NULL, '리비아', 'COUNTRY'),
    ('MA', NULL, '모로코', 'COUNTRY'),
    ('MC', NULL, '모나코', 'COUNTRY'),
    ('MD', NULL, '몰도바', 'COUNTRY'),
    ('ME', NULL, '몬테네그로', 'COUNTRY'),
    ('MF', NULL, '생마르탱', 'COUNTRY'),
    ('MG', NULL, '마다가스카르', 'COUNTRY'),
    ('MH', NULL, '마셜 제도', 'COUNTRY'),
    ('MK', NULL, '북마케도니아', 'COUNTRY'),
    ('ML', NULL, '말리', 'COUNTRY'),
    ('MM', NULL, '미얀마', 'COUNTRY'),
    ('MN', NULL, '몽골', 'COUNTRY'),
    ('MO', NULL, '마카오', 'COUNTRY'),
    ('MP', NULL, '북마리아나 제도', 'COUNTRY'),
    ('MQ', NULL, '마르티니크', 'COUNTRY'),
    ('MR', NULL, '모리타니', 'COUNTRY'),
    ('MS', NULL, '몬트세랫', 'COUNTRY'),
    ('MT', NULL, '몰타', 'COUNTRY'),
    ('MU', NULL, '모리셔스', 'COUNTRY'),
    ('MV', NULL, '몰디브', 'COUNTRY'),
    ('MW', NULL, '말라위', 'COUNTRY'),
    ('MX', NULL, '멕시코', 'COUNTRY'),
    ('MY', NULL, '말레이시아', 'COUNTRY'),
    ('MZ', NULL, '모잠비크', 'COUNTRY'),
    ('NA', NULL, '나미비아', 'COUNTRY'),
    ('NC', NULL, '뉴칼레도니아', 'COUNTRY'),
    ('NE', NULL, '니제르', 'COUNTRY'),
    ('NF', NULL, '노퍽 섬', 'COUNTRY'),
    ('NG', NULL, '나이지리아', 'COUNTRY'),
    ('NI', NULL, '니카라과', 'COUNTRY'),
    ('NL', NULL, '네덜란드', 'COUNTRY'),
    ('NO', NULL, '노르웨이', 'COUNTRY'),
    ('NP', NULL, '네팔', 'COUNTRY'),
    ('NR', NULL, '나우루', 'COUNTRY'),
    ('NU', NULL, '니우에', 'COUNTRY'),
    ('NZ', NULL, '뉴질랜드', 'COUNTRY'),
    ('OM', NULL, '오만', 'COUNTRY'),
    ('PA', NULL, '파나마', 'COUNTRY'),
    ('PE', NULL, '페루', 'COUNTRY'),
    ('PF', NULL, '프랑스령 폴리네시아', 'COUNTRY'),
    ('PG', NULL, '파푸아뉴기니', 'COUNTRY'),
    ('PH', NULL, '필리핀', 'COUNTRY'),
    ('PK', NULL, '파키스탄', 'COUNTRY'),
    ('PL', NULL, '폴란드', 'COUNTRY'),
    ('PM', NULL, '생피에르 미클롱', 'COUNTRY'),
    ('PN', NULL, '핏케언 제도', 'COUNTRY'),
    ('PR', NULL, '푸에르토리코', 'COUNTRY'),
    ('PS', NULL, '팔레스타인', 'COUNTRY'),
    ('PT', NULL, '포르투갈', 'COUNTRY'),
    ('PW', NULL, '팔라우', 'COUNTRY'),
    ('PY', NULL, '파라과이', 'COUNTRY'),
    ('QA', NULL, '카타르', 'COUNTRY'),
    ('RE', NULL, '레위니옹', 'COUNTRY'),
    ('RO', NULL, '루마니아', 'COUNTRY'),
    ('RS', NULL, '세르비아', 'COUNTRY'),
    ('RU', NULL, '러시아', 'COUNTRY'),
    ('RW', NULL, '르완다', 'COUNTRY'),
    ('SA', NULL, '사우디아라비아', 'COUNTRY'),
    ('SB', NULL, '솔로몬 제도', 'COUNTRY'),
    ('SC', NULL, '세이셸', 'COUNTRY'),
    ('SD', NULL, '수단', 'COUNTRY'),
    ('SE', NULL, '스웨덴', 'COUNTRY'),
    ('SG', NULL, '싱가포르', 'COUNTRY'),
    ('SH', NULL, '세인트헬레나', 'COUNTRY'),
    ('SI', NULL, '슬로베니아', 'COUNTRY'),
    ('SJ', NULL, '스발바르 얀마옌', 'COUNTRY'),
    ('SK', NULL, '슬로바키아', 'COUNTRY'),
    ('SL', NULL, '시에라리온', 'COUNTRY'),
    ('SM', NULL, '산마리노', 'COUNTRY'),
    ('SN', NULL, '세네갈', 'COUNTRY'),
    ('SO', NULL, '소말리아', 'COUNTRY'),
    ('SR', NULL, '수리남', 'COUNTRY'),
    ('SS', NULL, '남수단', 'COUNTRY'),
    ('ST', NULL, '상투메 프린시페', 'COUNTRY'),
    ('SV', NULL, '엘살바도르', 'COUNTRY'),
    ('SX', NULL, '신트마르턴', 'COUNTRY'),
    ('SY', NULL, '시리아', 'COUNTRY'),
    ('SZ', NULL, '에스와티니', 'COUNTRY'),
    ('TC', NULL, '터크스 케이커스 제도', 'COUNTRY'),
    ('TD', NULL, '차드', 'COUNTRY'),
    ('TF', NULL, '프랑스령 남방 지역', 'COUNTRY'),
    ('TG', NULL, '토고', 'COUNTRY'),
    ('TH', NULL, '태국', 'COUNTRY'),
    ('TJ', NULL, '타지키스탄', 'COUNTRY'),
    ('TK', NULL, '토켈라우', 'COUNTRY'),
    ('TL', NULL, '동티모르', 'COUNTRY'),
    ('TM', NULL, '투르크메니스탄', 'COUNTRY'),
    ('TN', NULL, '튀니지', 'COUNTRY'),
    ('TO', NULL, '통가', 'COUNTRY'),
    ('TR', NULL, '튀르키예', 'COUNTRY'),
    ('TT', NULL, '트리니다드 토바고', 'COUNTRY'),
    ('TV', NULL, '투발루', 'COUNTRY'),
    ('TW', NULL, '대만', 'COUNTRY'),
    ('TZ', NULL, '탄자니아', 'COUNTRY'),
    ('UA', NULL, '우크라이나', 'COUNTRY'),
    ('UG', NULL, '우간다', 'COUNTRY'),
    ('UM', NULL, '미국령 군소 제도', 'COUNTRY'),
    ('US', NULL, '미국', 'COUNTRY'),
    ('UY', NULL, '우루과이', 'COUNTRY'),
    ('UZ', NULL, '우즈베키스탄', 'COUNTRY'),
    ('VA', NULL, '바티칸', 'COUNTRY'),
    ('VC', NULL, '세인트빈센트 그레나딘', 'COUNTRY'),
    ('VE', NULL, '베네수엘라', 'COUNTRY'),
    ('VG', NULL, '영국령 버진아일랜드', 'COUNTRY'),
    ('VI', NULL, '미국령 버진아일랜드', 'COUNTRY'),
    ('VN', NULL, '베트남', 'COUNTRY'),
    ('VU', NULL, '바누아투', 'COUNTRY'),
    ('WF', NULL, '월리스 푸투나', 'COUNTRY'),
    ('WS', NULL, '사모아', 'COUNTRY'),
    ('YE', NULL, '예멘', 'COUNTRY'),
    ('YT', NULL, '마요트', 'COUNTRY'),
    ('ZA', NULL, '남아프리카공화국', 'COUNTRY'),
    ('ZM', NULL, '잠비아', 'COUNTRY'),
    ('ZW', NULL, '짐바브웨', 'COUNTRY')
ON CONFLICT (code) DO NOTHING;
