-- 앱 사용자 기기 자격증명. 익명 사용자를 device_secret 해시로만 식별한다.
--
-- 클라이언트가 만든 installation_id는 식별자일 뿐 인증 수단이 아니다. 서버가 발급한
-- 32바이트 SecureRandom 시크릿의 SHA-256 해시만 인증에 쓴다. push_device의 관례
-- (credential_status 컬럼명, REVOKED와 revoked_at의 쌍 체크, ACTIVE 행 부분 unique
-- index)를 그대로 따르되 별도 테이블로 둔다. 푸시 토큰은 FCM/APNs가 소유하고 수시로
-- 갱신되는 반면 기기 자격증명은 우리가 발급·해지하는 인증 값이라 생명주기가 다르다.
-- 결정 배경은 docs/product/AUTH_DESIGN.md 3.2~3.3절과
-- docs/adr/0006-split-operator-and-device-authentication.md에 있다.
CREATE TABLE device_credential (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    installation_id         VARCHAR(64) NOT NULL,
    secret_hash             CHAR(64) NOT NULL,
    platform                VARCHAR(20) NOT NULL,
    credential_status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_used_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    revoked_at              TIMESTAMPTZ,

    CONSTRAINT fk_device_credential_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE,
    CONSTRAINT ck_device_credential_platform
        CHECK (platform IN ('IOS', 'ANDROID')),
    CONSTRAINT ck_device_credential_status
        CHECK (credential_status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT ck_device_credential_revoked_at
        CHECK ((credential_status = 'REVOKED') = (revoked_at IS NOT NULL)),
    CONSTRAINT ck_device_credential_installation_id
        CHECK (btrim(installation_id) <> '')
);

-- secret_hash는 SHA-256이라 salt가 없다. 같은 해시가 두 행에 있으면 두 기기가 같은
-- 시크릿을 공유한다는 뜻이므로 애초에 유일해야 하고, 이 unique index가 재발급 조회의
-- 조회 경로이기도 하다.
CREATE UNIQUE INDEX uq_device_credential_secret
    ON device_credential (secret_hash);

-- ACTIVE 자격증명이 있는 installation_id로 재등록하면 거절한다(409). REVOKED된
-- installation_id는 재사용을 막지 않는다. 기기를 잃고 새로 등록하는 경로를 열어 둔다.
CREATE UNIQUE INDEX uq_active_device_installation
    ON device_credential (installation_id) WHERE credential_status = 'ACTIVE';

CREATE INDEX device_credential_user_idx
    ON device_credential (user_id) WHERE credential_status = 'ACTIVE';

COMMENT ON TABLE device_credential IS
    '앱 사용자 기기 자격증명. device_secret은 평문으로 저장하지 않고 SHA-256 해시만 저장한다.';
COMMENT ON COLUMN device_credential.secret_hash IS
    'device_secret의 SHA-256 해시(hex, 64자). 256bit 랜덤 값이라 무차별 대입이 불가능하므로 salt 없는 고정 해시로 인덱스 조회를 가능하게 한다.';
COMMENT ON COLUMN device_credential.last_used_at IS
    '토큰 재발급이 성공할 때마다 갱신한다. 유휴 기기 자격증명 정리 판단에 쓴다.';
